#+title: =Leetcode=, задача =3362=

Ця задача продовжує серію задач на /інкрементний масив/ (/difference array/), а саме, [[https://leetcode.com/problems/zero-array-transformation-i/solutions/6540070/difference-array-first-knowledge/][3355]] та [[https://leetcode.com/problems/zero-array-transformation-ii/solutions/6565954/tricky/][3356]]
(див. також [[file:src/bin/task3356.rs][task3356.rs]]).

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task3362.rs
  <<task3362:Декларації>>

  <<task3362:Визначення>>

  fn max_removal(mut nums: Vec<i32>, queries: Vec<Vec<i32>>) -> i32 {
      <<task3362:Дії>>
  }

  fn main() {
      <<task3362:Отримання-даних>>
      println!("{}", max_removal(nums, queries));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task3362:Декларації
  use std::{env, fs, io::{self, BufRead}};
#+end_src

#+begin_src rust :noweb-ref task3362:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let file = fs::File::open(&args[1]).unwrap();
  let mut lines = io::BufReader::new(file)
      .lines()
      .map(|line| line.unwrap());
  let nums = lines.next().unwrap()
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
  let queries = lines.next().unwrap()
      .strip_prefix('[').unwrap()
      .strip_suffix(']').unwrap()
      .split("],[")
      .map(|row| row
           .trim_start_matches('[')
           .trim_end_matches(']')
           .split(',')
           .map(|item| item.parse().unwrap())
           .collect())
      .collect();
#+end_src

Для зручності позначимо розмір масива ~nums~ як ~n~.

#+begin_src rust :noweb-ref task3362:Дії
  let n = nums.len();
#+end_src

* Черга запитів

Алгоритм спираєтся на впорядковану /чергу запитів/, яка представлена у вигляді впорядкованої сумки
(~BinaryHeap~).

#+begin_src rust :noweb-ref task3362:Декларації
  use std::collections::BinaryHeap;
  use std::cmp::Reverse;
#+end_src

#+begin_src rust :noweb-ref task3362:Дії
  let mut queries: BinaryHeap<_> = queries.into_iter()
      .map(|q| Reverse((q[0] as usize, q[1] as usize))).collect();
#+end_src

* Інкрементний масив

Перетворимо вектор джерела на інкрементний масив, в якому усі елементи, окрім самого першого (~nums[0]~),
представлені різницею між цим та попереднім значенням. Для ефективності усі перетворення виконуємо прямо
в джерелі. Однак, оскільки інкрементний масив вимагає одного додаткового елемента, просто додамо ~0~ в
кінець масива.

#+begin_src rust :noweb-ref task3362:Дії
  nums.push(0);
  for i in (1..=n).rev() { nums[i] -= nums[i-1]; }
#+end_src

* Пошук рішення

Шукатимо рішення в безумовному циклі, який припиняється поверненням з функції в середині тіла
цикла. Таким чином, код після цикла є недоступним.

Особливістю задачі є те, що треба повернути не мінімальну кількість необхідних запитів, а максимальну
кількість запитів, яку можна викинути. Тому при підрахунку результат будемо зменшувати від початкової
кількості запитів, а не збільшувати.

#+begin_src rust :noweb yes :noweb-ref task3362:Дії
  let mut result = queries.len() as i32;
  let mut i = 0;
  loop {
      <<task3362:Знайти-рішення>>
      result -= 1;
  }
#+end_src

Оскільки метою є перетворення масива-джерела на нульовий, знайдемо перший ненульовий елемент. Для цього
відтворюємо головні значення з різниць. Неочевидною особливістю тут є те, що при ефективному обчисленні
результата запиту достатньо зменшувати одразу усі елементи в діапазоні запиту, і розглядати від'ємні
значення результата як "нульові", оскільки можна вважати, що зменшення цих значень не виконувалось. Тому
при пошуку достатньо знайти перше позитивне значення масива.

#+begin_src rust :noweb-ref task3362:Знайти-рішення
  while i < n && nums[i] <= 0 { i += 1; nums[i] += nums[i-1]; }
#+end_src

Якщо ми досягли кінця масива, то рішення знайдено, і можемо просто повернути результат.

#+begin_src rust :noweb-ref task3362:Знайти-рішення
  if i == n { return result; }
#+end_src

Далі ми маємо знайти найліпший запит, що підходить. Для цього ми спочатку знаходимо перший запит, а потім
намагаємось його поліпшити. Результатом є значення ~r~ правої межи найліпшого запиту.

Для простоти одразу визначимо безумовний цикл, в якому виконується пошук першого запиту. Результат такого
цикла повертається в операторі ~break~.

#+begin_src rust :noweb yes :noweb-ref task3362:Знайти-рішення
  let mut r = loop {
      <<task3362:Знайти-перший-запит>>
      break r;
  };

  <<task3362:Знайти-найліпший-запит>>
#+end_src

Виконуємо знайдений найліпший запит, враховуючи, що ліва межа визначається поточним значенням ~i~.

#+begin_src rust :noweb-ref task3362:Знайти-рішення
  nums[i] -= 1; nums[r+1] += 1;
#+end_src

* Пошук першого запита

Перший запит, що підходить, мусить мати ліву межу ~l~ до поточного індекса ~i~ (~l<=i~), і праву межу
після нього (~r>=i~).

Перш, ніж перевірити ці умови, перевіримо, що черга не є пустою. Якщо ми не можемо отримати черговий
запит з пустої черги, то рішення нема, тому повертаємо ~-1~.

#+begin_src rust :noweb-ref task3362:Знайти-перший-запит
  let Some(Reverse((l, r))) = queries.pop() else { return -1; };
#+end_src

Якщо ~l>i~, то ми не зможемо "занулити" поточне значення ~nums[i]~, рішення нема, тому повертаємо ~-1~.

#+begin_src rust :noweb-ref task3362:Знайти-перший-запит
  if l > i { return -1; }
#+end_src

Якщо ~r<i~, то формально рішення все ще існує, але такий запит не має сенсу і може не враховуватись. Тому
просто продовжимо пошук першого значення.

#+begin_src rust :noweb-ref task3362:Знайти-перший-запит
  if r < i { continue; }
#+end_src

* Пошук найліпшого запита

Поки в черзі залишаються запити, для яких ~l'<=i~, ми можемо поліпшити запит, якщо для них права межа
знаходиться далі, ніж ~r~ (тобто, ~r'>r~). Якщо таких значень нема (включаючи варіант, коли черга стає
пустою), то поточний запит є найліпшим. Тому переберемо наступні запити в циклі.

Зауважимо, що якщо запит підходить, але не є найліпшим, його треба повернути в чергу. Але це неможливо
зробити одразу, оскільки викличе нескінчений цикл. Тому зберігаємо запити, які підходять, але не є
найліпшими, в проміжному векторі, і після завершення повертаємо їх до черги. Для простоти ми зберігаємо
тільки праву межу ~r~ в векторі ~rs~, обмежуючі нові запити зліва значенням поточного індексу ~i~.

#+begin_src rust :noweb yes :noweb-ref task3362:Знайти-найліпший-запит
  let mut rs = Vec::new();
  while let Some(&Reverse((l, r_))) = queries.peek() {
      if l > i { break; } else { queries.pop(); }
      <<task3362:Поліпшити-запит>>
  }
  for r in rs { queries.push(Reverse((i, r))); }
#+end_src

Якщо в черговому запиті права межа знаходиться до ~i~ (~r'<i~), то цей запит не впливає на результат, і
його можна відкинути.

#+begin_src rust :noweb-ref task3362:Поліпшити-запит
  if r_ < i { continue; }
#+end_src

Якщо черговий запит краще поточного, зберігаємо поточний запит в ~rs~ і поліпшуємо ~r~ (~r<-r'~), в
іншому випадку зберігаємо в ~rs~ черговий запит.

#+begin_src rust :noweb-ref task3362:Поліпшити-запит
  if r_ > r { rs.push(r); r = r_; } else { rs.push(r_); }
#+end_src

