#+title: =Leetcode=, задача =3105=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task3105.rs
  <<task3105:Декларації>>

  <<task3105:Визначення>>

  pub fn longest_monotonic_subarray(nums: Vec<i32>) -> i32 {
      <<task3105:Дії>>
  }

  fn main() {
      <<task3105:Отримання-даних>>
      println!("{}", longest_monotonic_subarray(nums));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task3105:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task3105:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let nums: Vec<i32> = args[1]
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
#+end_src

* Особливі випадки

Якщо довжина масива менше ~2~, то весь масив є монотонним, і результат дорівнює довжині самого масиву.

#+begin_src rust :noweb-ref task3105:Дії
  if nums.len() < 2 { return nums.len() as i32; }
#+end_src

* Початкові значення

Результат у будь-якому разі не може бути менше ~1~.

#+begin_src rust :noweb-ref task3105:Дії
  let mut result = 1;
#+end_src

Визначимо поточний /напрямок/ (=dir=) порівнявши два перших значення.

#+begin_src rust :noweb-ref task3105:Дії
  let mut dir = nums[0].cmp(&nums[1]);
#+end_src

Визначимо довжину поточної /серії/ (=run=). Якщо початковий напрямок є рівним (~Ordering::Equal~), ми
одразу отримаємо серію довжини ~1~, однак, це не більше, ніж щойно встановлений результат, тому ми можемо
його проігнорувати, однак, довжина наступної серії при цьому має дорівнювати ~0~. В іншому випадку ми
маємо початок /суворої/ (суворо зростаючої або суворо зпадаючої) серії, і її довжина вже має дорівнювати ~1~.

#+begin_src rust :noweb-ref task3105:Декларації
  use std::cmp::Ordering;
#+end_src

#+begin_src rust :noweb-ref task3105:Дії
  let mut run = if dir == Ordering::Equal { 0 } else { 1 };
#+end_src

* Перебір значень

Перебираємо значення, починаючи з наступного за першим, і закінчуючи передостаннім.

#+begin_src rust :noweb yes :noweb-ref task3105:Дії
  for i in 1..nums.len()-1 {
      <<task3105:Обробити-значення>>
  }
#+end_src

Поточне значення в будь-якому разі подовжує серію (навіть, якщо вона була нульовою після попереднього
циклу).

#+begin_src rust :noweb-ref task3105:Обробити-значення
  run += 1;
#+end_src

Визначимо наступний напрямок (~ndir~), порівнявши поточне значення з наступним.

#+begin_src rust :noweb-ref task3105:Обробити-значення
  let ndir = nums[i].cmp(&nums[i+1]);
#+end_src

Якщо наступний напрямок є рівним, або не співпадає з поточним, ми завершуємо серію. При цьому збільшуємо
результат, якщо нова серія довше за попередні, а потім встановлюємо новий напрямок, як поточний, а
довжину наступної серії визначаємо в залежності від напрямку.

#+begin_src rust :noweb-ref task3105:Обробити-значення
  if ndir == Ordering::Equal || ndir != dir {
      result = result.max(run);
      dir = ndir;
      run = if dir == Ordering::Equal { 0 } else { 1 };
  }
#+end_src

* Останній елемент і завершення

Останній елемент не має наступного, тому він у будь якому разі завершує поточну серію. Нам не треба
обчислювати параметри нової серії, достатньо лише збільшити результат, якщо довжина поточної серії
більше. При цьому враховуємо, що останній елемент завжди входить до серії, тому довжина для порівняння
завжди на ~1~ більше поточної.

#+begin_src rust :noweb-ref task3105:Дії
  result.max(run + 1)
#+end_src
