#+title: =Leetcode=, задача =3170=

* Опис задачі

Функція ~clear_stars~ отримує рядок ~s~, що складається з малих літер англійського алфавіту та зірочок
(~*~).  Кожна зірочка видаляє найменший з попередніх символів, якщо він існує. Функція повертає
результуючий рядок після обробки всіх зірочок.

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task3170.rs
  <<task3170:Декларації>>

  <<task3170:Визначення>>

  pub fn clear_stars(s: String) -> String {
      <<task3170:Дії>>
  }

  fn main() {
      <<task3170:Отримання-даних>>
      println!("{}", clear_stars(s));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task3170:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task3170:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let s = args[1].clone();
#+end_src

* Пошук рішення

Створимо впорядковану сумку ~queue~ (~BinaryHeap~), в якій будемо зберігати усі символи, окрім зірочки,
разом з їх позиціями. При цьому ми впорядковуємо пари так, щоб символ зростав, а його позиція
зменшувалась.

#+begin_src rust :noweb yes :noweb-ref task3170:Декларації
  use std::collections::BinaryHeap;
  use std::cmp::Reverse;
#+end_src

#+begin_src rust :noweb yes :noweb-ref task3170:Дії
  let mut queue = BinaryHeap::new();
#+end_src

Обробляємо по черзі усі символи рядка джерела ~s~. Якщо черговий символ є зірочкою, то вилучаємо останній
найменший символ, інакше додаємо черговий символ до черги.

#+begin_src rust :noweb yes :noweb-ref task3170:Дії
  for (i, c) in s.bytes().enumerate() {
      if c == b'*' {
          <<task3170:Вилучити-символ>>
      } else {
          queue.push((Reverse(c), i));
      }
  }
#+end_src

В кінці перебираємо чергу у довільному порядку і заповнюємо результат. Для оптимізації ми не змінюємо
індекси символів при [[id:f59061fd-ca24-4010-8b50-133ada178e61][вилученні]], тому результат спочатку має містити простір для усіх можливих
індексів. Потім ми прибираємо усі "пусті" місця (з ~0~), щоб стиснути результат.

#+begin_src rust :noweb yes :noweb-ref task3170:Дії
  let mut result = vec![0; s.len()];
  for (Reverse(c), i) in queue { result[i] = c; }
  let result = result.into_iter().filter(|&c| c != 0).collect();
  String::from_utf8(result).unwrap()
#+end_src

* Вилучення символа
:PROPERTIES:
:ID:       f59061fd-ca24-4010-8b50-133ada178e61
:END:

Обрати символ для вилучення просто, це перший символ у черзі, якщо він є. Але вилучення символа з черги є
нетривіальним, оскільки необхідно зменшити індекси усіх елементів, які йдуть після обраного
символа. Однак, впорядкована черга не допускає зміни "по місцю".

Тому, для ефективносі, залишаємо індекси без змін, просто виштовхуючи черговий символ з черги.

#+begin_src rust :noweb yes :noweb-ref task3170:Вилучити-символ
  queue.pop();
#+end_src

* Тести

#+begin_src rust :noweb yes :noweb-ref task3170:Визначення
  #[cfg(test)]
  mod tests {
      use super::*;

      #[test]
      fn test_basic_1() {
          let s = "leet**cod*e".to_string();
          let result = clear_stars(s);
          assert_eq!(result, "ltode");
      }

      #[test]
      fn test_basic_2() {
          let s = "erase*****".to_string();
          let result = clear_stars(s);
          assert_eq!(result, "");
      }

      #[test]
      fn test_no_stars() {
          let s = "abcde".to_string();
          let result = clear_stars(s);
          assert_eq!(result, "abcde");
      }

      #[test]
      fn test_only_stars() {
          let s = "****".to_string();
          let result = clear_stars(s);
          assert_eq!(result, "");
      }

      #[test]
      fn test_alternating() {
          let s = "a*b*c*d*e*".to_string();
          let result = clear_stars(s);
          assert_eq!(result, "");
      }

      #[test]
      fn test_consecutive_stars() {
          let s = "abc***de**f".to_string();
          let result = clear_stars(s);
          assert_eq!(result, "f");
      }

      #[test]
      fn test_stars_at_start() {
          let s = "**abc".to_string();
          let result = clear_stars(s);
          assert_eq!(result, "abc");
      }

      // fn test_from_file_impl(filename: &str) {
      //     use std::fs::File;
      //     use std::io::{BufRead, BufReader};

      //     let file = File::open(filename).unwrap();
      //     let mut lines = BufReader::new(file).lines();
          
      //     let input = lines.next().unwrap().unwrap();
      //     let expected = lines.next().unwrap().unwrap();
          
      //     let result = clear_stars(input);
      //     assert_eq!(result, expected);
      // }

      // #[test]
      // fn test_from_file_1() {
      //     test_from_file_impl("./task3170_1.txt");
      // }

      // #[test]
      // fn test_from_file_2() {
      //     test_from_file_impl("./task3170_2.txt");
      // }

      // #[test]
      // fn test_from_file_3() {
      //     test_from_file_impl("./task3170_3.txt");
      // }
  }
#+end_src 
