#+title: =Leetcode=, задача =3372=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task3372.rs
  <<task3372:Декларації>>

  <<task3372:Визначення>>

  pub fn max_target_nodes(edges1: Vec<Vec<i32>>, edges2: Vec<Vec<i32>>, k: i32) -> Vec<i32> {
      <<task3372:Дії>>
  }

  fn main() {
      <<task3372:Отримання-даних>>
      println!("{:?}", max_target_nodes(edges1, edges2, k));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task3372:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task3372:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let edges1: Vec<Vec<i32>> = args[1]
      .trim_matches(|c| c == '[' || c == ']')
      .split("],[")
      .map(|s| s.trim_matches(|c| c == '[' || c == ']')
          .split(',')
          .filter_map(|n| n.parse().ok())
          .collect())
      .collect();
  let edges2: Vec<Vec<i32>> = args[2]
      .trim_matches(|c| c == '[' || c == ']')
      .split("],[")
      .map(|s| s.trim_matches(|c| c == '[' || c == ']')
          .split(',')
          .filter_map(|n| n.parse().ok())
          .collect())
      .collect();
  let k: i32 = args[3].parse().unwrap();
#+end_src

* Побудова графа

Особливість алгоритма в тому, що нам в кінці потрібно зібрати відповідь у певному порядку. Тому
представлятимо граф у вигляді вектору, не мапи. При цьому ми маємо спочатку визначити загальну кількість
вузлів ~n~.

#+begin_src rust :noweb-ref task3372:Визначення
  fn graph(edges: Vec<Vec<i32>>) -> Vec<Vec<usize>> {
      let n = edges.iter().map(|edge| edge[0].max(edge[1])).max().unwrap() as usize + 1;
      edges.into_iter()
          .fold(vec![Vec::new(); n], |mut graph, edge| {
              let (from, to) = (edge[0] as usize, edge[1] as usize);
              graph[from].push(to);
              graph[to].push(from);
              graph
          })
  }
#+end_src

* Пошук ступіню

/=k=-ступенем/ (або просто ступінем) вузла будемо вважати розмір ~k~-околиці, тобто, кількість вузлів,
які можна досягнути з нього за ~k~ кроків. Функція ~degree~ знаходить ступіть вузла ~root~ для заданого
графа ~graph~.

Зауважимо, що початковий вузол також входить в околицю, тому ступінь вузла дорівнює, щонайменше,
одиниці.

Обробимо також особливий випадок ~k=0~

#+begin_src rust :noweb yes :noweb-ref task3372:Визначення
  fn degree(graph: &Vec<Vec<usize>>, root: usize, k: i32) -> i32 {
      let mut result = 1;
      <<task3372:degree:Дії>>
      result as i32
  }
#+end_src

Для ефективності зберігатимо у векторі ~is_visited~ ознаки вузлів, які були відвідані.

#+begin_src rust :noweb-ref task3372:degree:Дії
  let mut is_visited = vec![false; graph.len()];
#+end_src

Помітимо початковий вузол, як відвіданий.

#+begin_src rust :noweb-ref task3372:degree:Дії
  is_visited[root] = true;
#+end_src

Створимо чергу обробки вузлів, яка включає не тільки вузол, але і його відстань від початкового
вузла. Спочатку черга містить початковий вузол з нульовою відстанню.

#+begin_src rust :noweb-ref task3372:degree:Дії
  let mut queue = vec![(root, 0)];
#+end_src

Перебираємо чергу до повного спустошення, обробляючи поточний вузол.

#+begin_src rust :noweb yes :noweb-ref task3372:degree:Дії
  while let Some((node, d)) = queue.pop() {
      <<task3372:degree:Обробити-вузол>>
  }
#+end_src

Для ефективності вважаємо, що ~k>1~ (випадок ~k=0~ розглянуто [[id:001fcff5-f699-4f72-a543-7132b4056250][окремо]]), при цьому тримаємо в черзі тільки
вузли з відстанню ~d<k~. Таким чином, для обраного вузла завжди можна зробити ще один крок.

Для ефективності у часі (за рахунок пам'яті) зберемо окремо усіх сусідів вузла, які ще не відвідані.

#+begin_src rust :noweb-ref task3372:degree:Обробити-вузол
  let nodes: Vec<_> = graph[node].iter().filter(|&&node| !is_visited[node]).collect();
#+end_src

Збільшуємо результат на кількість сусідів, які ще не відвідано.

#+begin_src rust :noweb-ref task3372:degree:Обробити-вузол
  result += nodes.len();
#+end_src

Якщо відстань поточного вузла менше ~k-1~, додаємо до черги усіх його сусідів, які ще не відвідано, зі
збілшеною відстанню, водночас помічаємо ці вузли як відвідані. В іншому випадку не додаємо вузли до
черги, але відмічаємо їх, як відвідані. Таке розгалудження має оптимізувати обчислення в циклі.

#+begin_src rust :noweb-ref task3372:degree:Обробити-вузол
  if d < k-1 {
      for &node in nodes.into_iter() { queue.push((node, d+1)); is_visited[node] = true; }
  } else {
      for &node in nodes.into_iter() { is_visited[node] = true; }
  }
#+end_src

* Особливий випадок ~k=0~
:PROPERTIES:
:ID:       001fcff5-f699-4f72-a543-7132b4056250
:END:

Для ефективності рішення вимагає ~k>1~, але в такому випадку ми маємо обробити особливим чином випадок
~k=0~. В цьому випадку структура графів не важлива, оскільки ступінь кожного вузла дорівнює
~1~. Складність тут тільки в тому, що нам все ще потрібно отримати кількість вузлів першого графа, для
чого потрібно проаналізувати ~edges1~. Просто отримаємо максимальний номер вузла в ~edges1~.

#+begin_src rust :noweb-ref task3372:Дії
  if k == 0 {
      let n = edges1.into_iter().map(|edge| edge[0].max(edge[1])).max().unwrap() as usize + 1;
      return vec![1; n];
  }
#+end_src 

* Пошук найбільшого ступіню другого графа
:PROPERTIES:
:ID:       5fe68856-dcf8-43ff-b242-7284c4499286
:END:

При пошуку максимального ступіню у другому графі розмір околиці дорівнює ~k-1~, і ми маємо врахувати
окремо випадок ~k=1~, який схожий на [[id:001fcff5-f699-4f72-a543-7132b4056250][особливий випадок ~k=0~]], який ми розглянули раніше. В цьому випадку
найбільший ступінь другого графу завжди дорівнює ~1~.

#+begin_src rust :noweb-ref task3372:Дії
  let d = if k == 1 { 1 } else {
      let g = graph(edges2);
      (0..g.len()).map(|n| degree(&g, n, k-1)).max().unwrap()
  };
#+end_src 

* Пошук рішення

Для отримання рішення достатньо до =k=-ступіню кожного вузла в першому графі додати максимальний ступінь
~d~ для =k-1=-околиці у другому графі (яке ми знайшли [[id:5fe68856-dcf8-43ff-b242-7284c4499286][раніше]], оскільки одне ребро буде додано під час
з'єднання графів.

#+begin_src rust :noweb-ref task3372:Дії
  let g = graph(edges1);
  (0..g.len()).map(|n| degree(&g, n, k) + d).collect()
#+end_src 
