#+title: =Leetcode=, задача =2542=

Див. тестові файли [[file:task2542_1.txt][task2542_1.txt]], [[file:task2542_2.txt][task2542_2.txt]], [[file:task2542_3.txt][task2542_3.txt]]

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task2542.rs
  <<task2542:Декларації>>

  <<task2542:Визначення>>

  fn max_score(nums1: Vec<i32>, nums2: Vec<i32>, k: i32) -> i64 {
      <<task2542:Дії>>
  }

  fn main() {
      <<task2542:Отримання-даних>>
      println!("{}", max_score(nums1, nums2, k));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task2542:Декларації
  use std::{env, fs, io::{self, BufRead}};
#+end_src

#+begin_src rust :noweb-ref task2542:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let file = fs::File::open(&args[1]).unwrap();
  let mut lines = io::BufReader::new(file)
      .lines()
      .map(|line| line.unwrap());
  let nums1 = lines.next().unwrap()
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
  let nums2 = lines.next().unwrap()
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
  let k = lines.next().unwrap().parse().unwrap();
#+end_src

Встановимо синонім розміру масивів ~n~.

#+begin_src rust :noweb-ref task2542:Дії
  let n = nums1.len();
  println!("{}", n);
#+end_src

Вирівняємо тип ~k~.

#+begin_src rust :noweb-ref task2542:Дії
  let k = k as usize;
#+end_src

* Формування масиву пар

Ідея рішення заключається в тому, щоб пов'язати значення з обох масивів в пари, відсортувати отриманий
масив пар, а потім перебирати елементи по зростанню другого компонента пари, намагаючись знайти найбільшу
суму з залишків перших компонент.

Тому спочатку знайдемо відсортований перелік пар.

#+begin_src rust :noweb-ref task2542:Дії
  let mut pairs = (0..n)
      .map(|i| (nums1[i], nums2[i]))
      .collect::<Vec<_>>();
  pairs.sort_by_key(|pair| pair.1);
  println!("{}", pairs.len());
#+end_src

* Пошук залишків

Перебираємо пари в отриманому порядку зі зростанням другого компонента. Кожний раз ми автоматично
визначаємо мінімальне значення фрагмента в другому масиві, і залишається лише знайти максимальне значення
суми з ~k~ елементів першого масиву. В результаті треба відібрати значення з максимальним добутком.

Тут важливо правильно задати межі перебору, оскільки отримати ~k~ компонент можна, тільки якщо індекс не
більше ~n-k~.

Враховуємо, що при множенні може виникнути переповнення, тому перед обчисленням добутку треба привести
обидва значення до ~i64~.

#+begin_src rust :noweb yes :noweb-ref task2542:Дії
  (0..=n-k)
      .inspect(|i| if i % 1000 == 0 { println!("{}", i); })
      .map(|i| {
          let mut result = 0;
          <<task2542:Знайти-найбільшу-суму-фрагмента-залишку>>
          result * pairs[i].1 as i64
      })
      .max().unwrap()
#+end_src

Для знаходження найбільшої суми залишку перетворюємо його на впорядковану сумку (~BinaryHeap~).

#+begin_src rust :noweb-ref task2542:Декларації
  use std::collections::BinaryHeap;
#+end_src

#+begin_src rust :noweb-ref task2542:Знайти-найбільшу-суму-фрагмента-залишку
  let mut rest = pairs[i..].iter().map(|pair| pair.0).collect::<BinaryHeap<_>>();
#+end_src

Після цього знаходимо суму ~k~ найбільших елементів залишку, оскільки вони утворюють найкращий фрагмент.

# begin_src rust :noweb-ref task2542:Знайти-найбільшу-суму-фрагмента-залишку
  result = rest.into_iter().take(k).map(|i| i as i64).sum();
#+end_src

#+begin_src rust :noweb-ref task2542:Знайти-найбільшу-суму-фрагмента-залишку
  for _ in 0..k {
      result += rest.pop().unwrap() as i64;
  }
#+end_src

