#+title: =Leetcode=, задача =2698=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task2698.rs
  <<task2698:Декларації>>

  <<task2698:Визначення>>

  fn punishment_number(n: i32) -> i32 {
      <<task2698:Дії>>
  }

  fn main() {
      <<task2698:Отримання-даних>>
      println!("{}", punishment_number(n));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task2698:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task2698:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let n = args[1].parse().unwrap();
#+end_src

* Перевірка розбиття

Розбиття шукається рекурсивно за допомогою /трасування з поверненням/ (=Back Trace=). Аргументами функції
~is_parted~ (=Is PARTitionable=) є:

- послідовність цифр ~ds~ (=Digits Series=);
- накопичувач ~a~ (=Accumulator=), в якому накопичується попередня сума фрагментів;
- число-еталон ~n~, з яким порівнюється накопичувач ~a~.

#+begin_src rust :noweb yes :noweb-ref task2698:Визначення
  fn is_parted(ds: &[usize], a: usize, n: usize) -> bool {
      <<task2698:is-parted:Дії>>
  }
#+end_src

Якщо послідовність цифр пуста, ми досягли кінця, і результат обчислюється як порівняння накопичувача з еталоном.

#+begin_src rust :noweb-ref task2698:is-parted:Дії
  if ds.is_empty() { return a == n; }
#+end_src

В іншому випадку перебираємо фрагменти послідовності ~ds~, обчислюючи в /локальному накопичувачі/ ~la~
(=Local Accumulator=) проміжну суму. На першому кроці, при скануванні (~scan~) ми формуємо пари із
залишку послідовності ~ds[i..]~ і локального акумулятора ~la~, а на другому етапі знаходимо будь-яку
пару, що підходить внаслідок рекурсивного перебору наступного рівня.

Важливо слідкувати за правильним формуванням залишку послідовності ~ds~: вона має починатися не з
наступного числа (~[1..]~), а з насупного елементу після виділення поточного фрагменту (~[i+1..]~, де ~i~
--- порядковий номер поточної цифри).

#+begin_src rust :noweb-ref task2698:is-parted:Дії
  ds.iter().enumerate()
      .scan(0, |la, (i, d)| {
          ,*la = 10 * *la + d;
          Some((&ds[i+1..], *la))
      })
      .any(|(ds, la)| is_parted(ds, a + la, n))
#+end_src

* COMMENT Відлагодження для одного значення

Для відлагодження просто перевіримо аргумент задачі. За умовами необхідно отримати послідовність цифр
квадрата числа (~n*n~) і підібрати розподіл для самого цього числа (~n~).

#+begin_src rust :noweb-ref task2698:Дії
  let ds: Vec<_> = (n*n).to_string()
      .chars()
      .map(|c| c.to_digit(10).unwrap() as usize)
      .collect();
#+end_src

* Пошук відповідних значень

Перебираємо усі значення від ~1~ до ~n~ включно, і відбираємо лише ті числа, для яких існують розбиття їх
квадратів, які дорівнюють самим числам. Після цього знайдемо суму квадратів таких чисел.

Для отримання послідовності цифр числа використовуємо трюк з ітераторами. Хоча таке рішення виглядає
неефективним по пам'яті, практика показує, що виграш некритичний, водночас, таке рішення є лексично
найпростішим.

#+begin_src rust :noweb-ref task2698:Дії
  (1..=n)
      .filter(|&i| {
          let ds: Vec<_> = (i*i).to_string()
              .chars()
              .map(|c| c.to_digit(10).unwrap() as usize)
              .collect();
          is_parted(&ds, 0, i as usize)
      })
      .map(|i| i*i)
      .sum()
#+end_src

