#+title: =Leetcode=, задача =3343=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task3343.rs
  <<task3343:Декларації>>

  <<task3343:Визначення>>

  fn count_balanced_permutations(num: String) -> i32 {
      <<task3343:Дії>>
  }

  fn main() {
      <<task3343:Отримання-даних>>
      println!("{}", count_balanced_permutations(num));
  }
#+end_src

* Отримання даних

Отримуємо просто вектор значень, який потім необхідно перетворити на перелік.

#+begin_src rust :noweb-ref task3343:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task3343:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let num = args[1].to_string();
#+end_src

Позначимо довжину рядка як ~n~.

#+begin_src rust :noweb-ref task3343:Дії
  let n = num.len();
#+end_src

* Модульна арифметика

За умовами задачі обчислення виконуються в модульній арифметиці.

#+begin_src rust :noweb-ref task3343:Визначення
  const MOD: u64 = 10u64.pow(9) + 7;
#+end_src

Для ефективного обчислення створимо таблиці розміру ~n+1~ (~i=(0..=n)~) для прямих (~fact~) та
/зворотніх/ (/inv/-erse) факторіалів (~inv_fact~). Прямі факторіали обчислюються як послідовне множення
кожного попереднього факторіала на поточне значення.

Для зворотніх факторіалів використовуємо проміжну таблицю зворотніх значень ~inv~, в якій для кожного ~i~
зберігається значення ~inv[i]~ таке, що ~i*inv[i]===1 (mod MOD)~. Обчислення зворотніх значень виглядає
як магія.

#+begin_src rust :noweb-ref task3343:Дії
  let (mut fact, mut inv, mut inv_fact) = (vec![1; n+1], vec![1; n+1], vec![1; n+1]);
  for i in 2..=n {
      fact[i] = fact[i-1] * i as u64 % MOD;
      inv[i] = MOD - MOD / i as u64 * inv[(MOD % i as u64) as usize] % MOD;
      inv_fact[i] = inv_fact[i-1] * inv[i] % MOD;
  }
#+end_src

* Отримання цільової суми

Обчислимо /цільову суму/ (/target sum/, =ts=), як суму усіх цифр в рядку джерела.

#+begin_src rust :noweb-ref task3343:Дії
  let ts: usize = num.chars().map(|c| c.to_digit(10).unwrap() as usize).sum();
#+end_src

* Перевірка непарної цільової суми і корекція парної цільової суми

Коли цільова сума не є парною, рішень не існує, повертаємо нульовий результат. В іншому випадку далі
розглядаємо, як цільову, половину цільової суми.

#+begin_src rust :noweb-ref task3343:Дії
  let ts = if ts % 2 == 1 { return 0; } else { ts / 2 };
#+end_src

* Отримання цільової довжини

/Цільовою довжиною/ (/target length/, =tl=) є половина довжини рядка джерела.

#+begin_src rust :noweb-ref task3343:Дії
  let tl = n / 2;
#+end_src

* Пошук рішення

Рішення шукаємо за допомогою динамічного програмування.

Визначимо ~dp[s][l]~ як кількість можливих рішень для довжини ~l~ та суми ~s~. З урахуванням додаткових
пустих значень загальний розмір матриці складає ~[tl+1]x[ts+1]~.

#+begin_src rust :noweb-ref task3343:Дії
  let mut dp = vec![vec![0; tl+1]; ts+1];
#+end_src

Для рядка нульової довжини з нульовою сумою дорівнює ~1~, тобто, вважаємо, що рядок нульової довжини з
нульовою сумою дає одне рішення.

#+begin_src rust :noweb-ref task3343:Дії
  dp[0][0] = 1;
#+end_src

Додатково зберемо статистику ~cs~ (/c/-ount-/s/) --- кількість раз, скільки кожна цифра зустрічається в
рядку джерела.

#+begin_src rust :noweb-ref task3343:Дії
  let mut cs = vec![0; 10];
#+end_src

Перебираємо усі цифри джерела, оновлюємо статистику ~cs~ та виконуємо крок перетворення ~dp~.

#+begin_src rust :noweb yes :noweb-ref task3343:Дії
  for d in num.chars().map(|c| c.to_digit(10).unwrap() as usize) {
      cs[d] += 1;
      <<task3343:Перетворити-dp>>
  } 
#+end_src

При перетворенні ~dp~ іде зворотній перебір суми і довжини від цільових до мінімальних значень. На
кожному кроці до кількості рішень для поточної пари ~(s, l)~ додається кількість рішень для суми,
зменшеної на значення цифри (~s-d~) і довжини на одиницю коротше (~l-1~).

#+begin_src rust :noweb-ref task3343:Перетворити-dp
  for s in (d..=ts).rev() { for l in (1..=tl).rev() { dp[s][l] = (dp[s][l] + dp[s-d][l-1]) % MOD; }}
#+end_src

Проміжним результатом є значення для цільової суми і довжини (~dp[ts][tl]~).

Домножимо проміжний результат на факторіали цільової довжини і її доповнення до довжини джерела
(факторіали кількості непарних і парних позицій). Таким чином ми враховуємо можливі перестановки цифр в
кожному з наборів.

#+begin_src rust :noweb-ref task3343:Дії
  let result = dp[ts][tl] * fact[tl] % MOD * fact[n-tl] % MOD;
#+end_src

Однак, цифри можуть повторюватись, тому для кожної цифри поділимо результат на факторіал кількості її
екземплярів в джерелі. Однак, оскільки ми виконуємо усі дії в модульній арифметиці, домножуємо результат
на зворотній факторіал.

#+begin_src rust :noweb-ref task3343:Дії
  cs.into_iter().fold(result, |result, c| result * inv_fact[c] % MOD) as i32
#+end_src
