#+title: =Leetcode=, задача =1931=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task1931.rs
  <<task1931:Декларації>>

  <<task1931:Визначення>>

  fn color_the_grid(m: i32, n: i32) -> i32 {
      <<task1931:Дії>>
  }

  fn main() {
      <<task1931:Отримання-даних>>
      println!("{}", color_the_grid(m, n));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task1931:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task1931:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let m = args[1].parse().unwrap();
  let n = args[2].parse().unwrap();
#+end_src

* Перевірка правильності
:PROPERTIES:
:ID:       24613e5b-e54b-4222-8ac5-d706a0e8e9ad
:END:

Мале значення ~m~ в обмеженнях задачі (~m<=5~) дають можливість отримати повний перелік можливих
стовпців.

Якщо закодувати кольори двбітними значеннями ~01~, ~10~ та ~11~. Значення ~00~ вважається "неправильним",
що дозволить швидко відбирати правильні комбінації, а пізніше --- відбирати сумісні стовпчики. Функція
~is_valid~ перевіряє, що стовпець є /правильним/ (/valid/) в тому сенсі, що в цьому значенні не може
зустрічатися двобітне значення ~00~.

#+begin_src rust :noweb-ref task1931:Визначення
  fn is_valid(v: u16, m: i32) -> bool { (0..m).all(|i| (v >> (2*i)) & 0b11 != 0) }
#+end_src

* Отримання переліку стовпців

Побудуємо перелік усіх можливих значень стовпців. Для цього переберемо усі значення від ~0~ до
~2^(2*m)-1~, відбираючи тільки правильні значення. Вважатимемо, що стовпець має код ~j~, якщо ~cols[j]~
містить стиснений стовпець.

#+begin_src rust :noweb-ref task1931:Дії
  let cols: Vec<_> = (0..2u16.pow(2*m as u32))
      .filter(|&v| is_proper(v, m))
      .collect();
#+end_src

Критерієм /стовпця, що підходить/ (/proper/), окрім того, що він є правильним стовпцем, є те, що в ньому
нема двох послідовних однакових значень. Функція ~is_proper~ перевіряє цю умову. Для ефективності ми
повторюємо тут умову правильного стовпця, а не використовуємо окремий виклик функції.

#+begin_src rust :noweb-ref task1931:Визначення
  fn is_proper(v: u16, m: i32) -> bool {
      (0..m).all(|i| {
          let v1 = v >> (2*i) & 0b11;
          let v2 = v >> (2*i+2) & 0b11;
          v1 != 0 && v1 != v2
      })
  }
#+end_src

Позначимо загальну кількість можливих стовпців як ~l=len(cols)=3^m~.

#+begin_src rust :noweb-ref task1931:Дії
  let l = cols.len();
#+end_src

* Пошук рішення

Рішення знаходиться методом динамічного програмування. Нехай ~dp[i][j]~ --- це кількість рішень для
матриці з ~n=i~ та останнім стовпцем з кодом ~j~. Відповідно до обмежень задачі маємо матрицю ~dp~
розміром не більше ніж ~1000x243~, що досить для рішення задачі.

Однак, особливістю алгоритма є те, що для обчислення кожного наступного рядка ~dp[i]~ достатньо знати
лише попередній рядок ~dp[i-1]~. В першому рядку ~dp[0]~ результатом рішення може бути будь-який стовпчик
матриці-джерела, тому усі значення в ~dp[0]~ дорівнюють ~1~.

Кожний наступний рядок ~dp'~ обчислюється як сума усіх значень попереднього рядка $dp$ для стовпців, які
не співпадають з поточним. Для перевірки співпадіння ми використовуємо ту ж саму функцію перевірки
правильного стовпця [[id:24613e5b-e54b-4222-8ac5-d706a0e8e9ad][is_valid]], однак перевіряємо /виключну логічну суму/ (E/x/clusive /or/, =xor=)
стовпців. Якщо два стовпця мають однаковий колір, то в результаті =xor= на цьому місці утворюється
двобітне значення ~00~, яке позначить неправильну комбінацію.

Остаточним результатом є проста сума значень в останньому рядку.

Відповідно до умов задачі використовуємо модульну арифметику.

#+begin_src rust :noweb-ref task1931:Визначення
  const MOD: u64 = 10u64.pow(9) + 7;
#+end_src

#+begin_src rust :noweb-ref task1931:Дії
  (0..n-1)
      .fold(vec![1; l], |dp, _| {
          (0..l).map(|i| {
              cols.iter().zip(dp.iter())
                  .filter_map(|(&c, &d)| if is_valid(c ^ cols[i], m) { Some(d) } else { None })
                  .reduce(|a, b| (a + b) % MOD).unwrap()
          }).collect()
      })
      .into_iter().reduce(|a, b| (a + b) % MOD).unwrap() as i32
#+end_src

