#+title: =Leetcode=, задача =2999=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task2999.rs
  <<task2999:Декларації>>

  <<task2999:Визначення>>

  fn number_of_powerful_int(start: i64, finish: i64, limit: i32, s: String) -> i64 {
      <<task2999:Дії>>
  }

  fn main() {
      <<task2999:Отримання-даних>>
      println!("{}", number_of_powerful_int(start, finish, limit, s));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task2999:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task2999:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let start = args[1].parse().unwrap();
  let finish = args[2].parse().unwrap();
  let limit = args[3].parse().unwrap();
  let s = args[4].to_string();
#+end_src

* Загальне рішення

Обчислимо кількість (~count~) потужних чисел для кінця (~finish~) і для початку (~start~)
діапазону. Врахуємо, що сам ~start~ входить до діапазону, тому брати треба попереднє значення
(~start-1~).

Зауважимо, що для підрахунку сам суфікс ~s~ не потрібен, достатньо передати його довжину ~sl~ (=s=-uffix
=l=-ength), щоб отримати тільки префікс числа, з яким і проводяться всі подальші обчислення.

#+begin_src rust :noweb-ref task2999:Дії
  let sl = s.len() as u32;
  let s = s.parse().unwrap();
  let l = limit as i64;
  count(finish, l, s, sl) - count(start-1, l, s, sl)
#+end_src

* Підрахунок префіксів

#+begin_src rust :noweb yes :noweb-ref task2999:Визначення
  fn count(x: i64, l: i64, s: i64, sl: u32) -> i64 {
      <<task2999:count:Дії>>
  }
#+end_src

Ми маємо підрахувати усі числа менше префікса ~x~, у яких жодна з цифр не перевищує межу ~l~
(=l=-imit). Для цього використовується динамічне программування, яке, однак, не вимагає масиву значень.

Розглянемо усі цифри префіксу в зворотньому порядку, справа наліво, коли ~i~ перебирається від останньої
(найменш значимої) до першої (найбільш значимої) цифри префіксу. Для кожного значення ~i~ підрахуємо
кількість ~result[i]~ можливих комбінацій цифр, у яких жодна з цифр не перевищує ~l~, а вся комбінація в
цілому не перевищує лексикографічно частини префікса ~x[i..]~.

Головна ідея в тому, що коли перша цифра префіксу ~x[i]~ більше межи ~l~ (~x[i]>l~), то підходять будь
які комбінації цифр. Позначимо таку загальну кількість комбінацій, де жодна з цифр не перевищує ~l~, як
~t[i]~ (=t=-otal). Помітимо, що ~t[i]=(l+1)^(n-i)~, однак, цей ступень ефективніше обчислювати
послідовними множеннями.

В іншому випадку, коли ~x[i]<=l~, то маємо два випадки. Для всіх комбінацій, де перша цифра суворо менше
~x[i]~, допустимі будь-які комбінації, і таких комбінацій усього ~x[i] * t[i+1]~. Для комбінацій, де
перша цифра дорівнює ~x[i]~, кількість в точності дорівнює попередньому рішенню ~result[i+1]~.

Зауважимо, що як для ~t~, так і для ~result~ нам потрібне лише попереднє значення, тому можна зберігати їх як
скаляри, а не як вектори.

Для повноти, спочатку вважаємо, що ~t=t[n]=1~.

#+begin_src rust :noweb yes :noweb-ref task2999:count:Дії
  let mut t = 1;
#+end_src

Для повноти треба визначити початкове значення ~result=result[n]~. Тут важливі два принципово різних
випадки.  Коли суфікс ~x~, що визначається як решта від ділення на ~10^sl~, більше ~s~, є, щонайменше,
хоча б одне рішення, інакше рішень немає.

#+begin_src rust :noweb yes :noweb-ref task2999:count:Дії
  let mut result = if x % 10_i64.pow(sl) < s { 0 } else { 1 };
#+end_src

Щоб отримати префікс, "відрізаємо" від значення ~x~ останні ~sl~ цифр (шляхом ділення на ступінь ~10^sl~) і перетворюємо його
на перелік цифр ~xp~ (=x= =p=-refix).

#+begin_src rust :noweb yes :noweb-ref task2999:count:Дії
  let xp = (x / 10_i64.pow(sl)).to_string();
  let xp = xp.chars().map(|c| c.to_digit(10).unwrap() as i64);
  for x in xp.rev() { if x > l { t *= l+1; result = t; } else { result += x * t; t *= l+1 } }
  result
#+end_src

* Оцінка складності

Час: ~O(Log(Finish)+Log(Limit)+∣S∣)~
Пам`ять: ~O(Log(Finish)+Log(Limit)+∣S∣)~

* Тестові випадки

#+begin_src text
  920604464841 898134311826379 9 "57713783178318"
#+end_src

Дає результат ~8~, очікується ~9~.

#+begin_src text
  437505374866 855623720085399 8 "144117632826787"
#+end_src

Дає результат ~0~, очікується ~1~.

#+begin_src text
  115483045258 762433231823372 1 "111111111111"
#+end_src

Дає результат ~8~, очікується ~7~.

#+begin_src text
  637005995780 518905354586422 8 "44324574"
#+end_src

Дає результат ~2770622~, очікується ~2770623~.

