#+title: =Leetcode=, задача =1415=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task1415.rs
  <<task1415:Декларації>>

  <<task1415:Визначення>>

  fn get_happy_string(n: i32, k: i32) -> String {
      let n = n as usize;
      let k = k as usize;
      <<task1415:Дії>>
  }

  fn main() {
      <<task1415:Отримання-даних>>
      println!("{}", get_happy_string(n, k));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task1415:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task1415:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let n = args[1].parse().unwrap();
  let k = args[2].parse().unwrap();
#+end_src

* Виклик пошуку і отримання результату

За допомогою рекурсивної функції ~find~ зберемо усі щасливі рядки у впорядкованій сумці (~BinaryHeap~), а
потім знайдемо рядок ~k~ в цьому порядку. Впорядкована сумка обрана тут лише заради ефективності
(складність вставки ~O(1)~), оскільки усі рядки в ній будуть унікальними.

Окрім сумки з результатом ми також передаємо довжину рядка ~n~ і проміжний (робочий) рядок ~happy~, в
якому буде накопичуватись черговий рядок результата.

В будь-якому щасливому рядку перша літера може бути будь-якою з алфавіту, тому викликаємо ~find~ в циклі
для усіх літер алфавіту.

#+begin_src rust :noweb-ref task1415:Декларації
  use std::collections::BinaryHeap;
#+end_src

#+begin_src rust :noweb-ref task1415:Дії
  let mut result = BinaryHeap::new();
  let mut happy = String::new();
  for c in "abc".chars() {
      happy.push(c); find(&mut result, n-1, &mut happy); happy.pop();
  }
#+end_src

При знаходженні рядка ~k~ спочатку вилучаємо і відкидаємо ~k-1~ рядків, після чого вилучаємо і повертаємо
останній рядок ~k~. При цьому враховуємо, що коли розмір сумки менше ~k~, повертаємо у якості результата
пустий рядок.

#+begin_src rust :noweb-ref task1415:Дії
  for _ in 0..k-1 { if result.pop().is_none() { return String::default(); } }
  result.pop().unwrap_or_default().0
#+end_src

* Рекурсивний пошук щасливих рядків

#+begin_src rust :noweb yes :noweb-ref task1415:Декларації
  use std::cmp::Reverse;
#+end_src

#+begin_src rust :noweb yes :noweb-ref task1415:Визначення
  fn find(result: &mut BinaryHeap<Reverse<String>>, n: usize, happy: &mut String) {
      <<task1415:find:Дії>>
  }
#+end_src

Коли лічильник ~n=0~, щасливий рядок знайдено, просто додаємо його до результата і повертаємось.

#+begin_src rust :noweb-ref task1415:find:Дії
  if n == 0 { result.push(Reverse(happy.clone())); return; }
#+end_src

Перебираємо усі літери алфавіту, які не співпадають з останньою літерою ~happy~, і для кожної літери
рекурсивно обчислюємо решту рядка.

#+begin_src rust :noweb-ref task1415:find:Дії
  for c in "abc".chars() {
      if c != happy.chars().last().unwrap() {
          happy.push(c); find(result, n-1, happy); happy.pop();
      }
  }
#+end_src

