#+title: =Leetcode=, задача =1004=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task1004.rs
  <<task1004:Декларації>>

  <<task1004:Визначення>>

  fn longest_ones(nums: Vec<i32>, k: i32) -> i32 {
      let mut result = 0;
      <<task1004:Дії>>
      result as i32
  }

  fn main() {
      <<task1004:Отримання-даних>>
      println!("{}", longest_ones(nums, k));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task1004:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task1004:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let nums: Vec<i32> = args[1]
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
  let k = args[2].parse().unwrap();
#+end_src

Для зручності визначимо розмір масива.

#+begin_src rust :noweb-ref task1004:Дії
  let n = nums.len();
#+end_src

* Обробка вікон

Для простоти початок вікна будемо перебирати з ~0~ до ~n~, однак з циклу можемо вийти достроково, коли
знайдемо останнє вікно.

#+begin_src rust :noweb yes :noweb-ref task1004:Дії
  for i in 0..n {
      <<task1004:Побудувати-вікно>>
  }
#+end_src

Нехай ~j~ позначає кінець вікна (на ~1~ далі за останнім елементом вікна), а ~c~ --- кількість нулів, які
було перетворено на одиниці. Починаємо з пустого вікна (~j=i~) і нульової кількості перетворених нулів.

#+begin_src rust :noweb-ref task1004:Побудувати-вікно
  let mut j = i;
  let mut c = 0;
#+end_src

Збільшуємо розмір вікна, переміщаючи ~j~ вперед, при цьому перевіряємо, що кількість перетворених нулів
менше ~k~, оскільки виконання будь-якої з цих умов означатиме, що вікно знайдено.

Для кожного нульового значення у вікні перетворюємо його, збільшуючи кількість перетворених нулів на ~1~.

#+begin_src rust :noweb-ref task1004:Побудувати-вікно
  while j < n && c < k {
      if nums[j] == 0 { c += 1; }
      j += 1;
  }
  if c == k { while j < n && nums[j] == 1 { j += 1; } }
#+end_src

Коли всі нулі перетворено, розширюємо вікно до наступного нульового значення (або до кінція масива, якщо
нульових значень більше немає), збільшуючи індекс кінця вікна.

#+begin_src rust :noweb-ref task1004:Побудувати-вікно
  if c == k { while j < n && nums[j] == 1 { j += 1; } }
#+end_src

Оновлюємо результат, якщо розмір побудованого вікна ~j - i~ більше поточного результата.

#+begin_src rust :noweb-ref task1004:Побудувати-вікно
  result = result.max(j - i);
#+end_src

Якщо ми досягли кінця масиву, нема сенсу перебирати вікна далі, тому перериваємо зовнішній цикл.

#+begin_src rust :noweb-ref task1004:Побудувати-вікно
  if j == n { break; }
#+end_src

