#+title: =Leetcode=, задача =1718=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task1718.rs
  <<task1718:Декларації>>

  <<task1718:Визначення>>

  fn construct_distanced_sequence(n: i32) -> Vec<i32> {
      let n = n as usize;
      <<task1718:Дії>>
  }

  fn main() {
      <<task1718:Отримання-даних>>
      println!("{:?}", construct_distanced_sequence(n));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task1718:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task1718:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let n = args[1].parse().unwrap();
#+end_src

* Виконання пошуку

Визначимо результат (~result~) як вектор фіксованої довжини ~2*n-1~, який спочатку заповнений нульовими
значеннями, а в результаті пошуку буде заповнений відповідною послідовністю.

#+begin_src rust :noweb-ref task1718:Дії
  let mut result = vec![0; 2*n-1];
#+end_src

При пошуку ми маємо враховувати значення, які вже використано (~is_used~), і перебирати лише значення поза
цим переліком. Хоча перелік значень, що використано, дуже схожий на впорядковану множину, краще зберігати
його у вигляді звичайного вектора логічних значень (~bool~) довжини ~n~.

#+begin_src rust :noweb-ref task1718:Дії
  let mut is_used = vec![false; n];
#+end_src

Сам пошук може завершитися невдало, але, схоже, задача сформульована так, що рішення завжди є. Тому ми
можемо просто проігнорувати логічну ознаку успіху пошуку.

#+begin_src rust :noweb-ref task1718:Дії
  find(&mut result, &mut is_used);
  result.into_iter().map(|v| v as i32).collect()
#+end_src

* Рекурсівний пошук

Пошук виконується рекурсивно за допомогою функції ~find~.

#+begin_src rust :noweb yes :noweb-ref task1718:Визначення
  fn find(result: &mut [usize], is_used: &mut [bool]) -> bool {
      <<task1718:find:Дії>>
  }
#+end_src

На черговому кроці рекурсії ми оперуємо лише з залишком вектора результата. Тому, якщо цей залишок
пустий, ми фактично знайшли необхідну послідовнісь, в такому разі повертаємо ознаку успішного пошуку.

#+begin_src rust :noweb-ref task1718:find:Дії
  if result.is_empty() { return true; }
#+end_src

Якщо перший елемент решти вже зайнято, пропускаємо його і спробуємо знайти результат для наступної решти.

#+begin_src rust :noweb-ref task1718:find:Дії
  if result[0] > 0 { return find(&mut result[1..], is_used); }
#+end_src

В іншому випадку перебираємо в зворотньому напрямку (щоб забезпечити лексикографічний максимум) усі
можливі значення (від ~1~ до ~n~), які ще не використано.

Для простоти ми не передаємо ~n~ до функції рекурсивного пошуку, оскільки ~n=is_used.len()~. Однак, коли
решта коротше, ніж ~n~, то ми не зможемо розмістити елементи більше ~result.len()-1~. Тому перебирати
потрібно менше з двох значень. З іншого боку, ця умова не застосовується для ~v=1~, яке не має пари, тому
останнє значення має бути не менше ~1~.

Достатньо знайти лише перше значення, яке надає можливе рішення.

#+begin_src rust :noweb yes :noweb-ref task1718:find:Дії
  (1..=is_used.len().min(result.len()-1).max(1)).rev()
      .any(|v| {
          <<task1718:find:Перевірити-значення>>
      })
#+end_src

Якщо значення вже використано, пропускаємо його.

#+begin_src rust :noweb yes :noweb-ref task1718:find:Перевірити-значення
  if is_used[v-1] { return false; }
#+end_src

Для кожного значення спочатку заповнюємо відповідним чином результат, встановлюємо ознаку використання
цього значення, виконуємо наступний крок рекурсивного пошуку, а потім повертаємо результат і ознаку
використання в початкове значення. Перше значення, для якого пошук буде успішним, завершує пошук.

Якщо значення ~v~, яке перевіряється, більше ~1~, то у нього має бути пара на відстані ~v~. Однак, якщо
це місце в результаті вже зайняте, то подальший пошук неможливий.

#+begin_src rust :noweb-ref task1718:find:Перевірити-значення
  if v > 1 && result[v] > 0 { return false; }
#+end_src

Зробимо наступний крок перевірки. Для цього встановлюємо чергове значення в результаті, для парних
значень (~v>1~) встановлюємо пару на відповідній відстані і відзначаємо те, що поточне значення вже
використано.

#+begin_src rust :noweb-ref task1718:find:Перевірити-значення
  result[0] = v;
  if v > 1 { result[v] = v; }
  is_used[v-1] = true;
#+end_src

Якщо пошук завершується успішно, просто завершуємо пошук успішно.

#+begin_src rust :noweb-ref task1718:find:Перевірити-значення
  if find(&mut result[1..], is_used) { return true; }
#+end_src

Якщо пошук завершився невдало, потрібно звільнити місце поточного значення, його пару (якщо вона є) і
ознаку використання поточного значення. Результат є невдалим.

#+begin_src rust :noweb-ref task1718:find:Перевірити-значення
  result[0] = 0;
  if v > 1 { result[v] = 0; }
  is_used[v-1] = false;
  false
#+end_src
