#+title: =Leetcode=, задача =3373=

Ця задача є розвитком задачі [[file:task3372.org][3372]], яку називатимемо /попередньою/.

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task3373.rs
  <<task3373:Декларації>>

  <<task3373:Визначення>>

  pub fn max_target_nodes(edges1: Vec<Vec<i32>>, edges2: Vec<Vec<i32>>) -> Vec<i32> {
      <<task3373:Дії>>
  }

  fn main() {
      <<task3373:Отримання-даних>>
      println!("{:?}", max_target_nodes(edges1, edges2));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task3373:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task3373:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let edges1 = args[1]
      .trim_matches(|c| c == '[' || c == ']')
      .split("],[")
      .map(|s| s.trim_matches(|c| c == '[' || c == ']')
          .split(',')
          .filter_map(|n| n.parse().ok())
          .collect())
      .collect();
  let edges2 = args[2]
      .trim_matches(|c| c == '[' || c == ']')
      .split("],[")
      .map(|s| s.trim_matches(|c| c == '[' || c == ']')
          .split(',')
          .filter_map(|n| n.parse().ok())
          .collect())
      .collect();
#+end_src

* Побудова графа

Особливість алгоритма в тому, що нам в кінці потрібно зібрати відповідь у певному порядку. Тому
представлятимо граф у вигляді вектору, не мапи. При цьому ми маємо спочатку визначити загальну кількість
вузлів ~n~.

#+begin_src rust :noweb-ref task3373:Визначення
  fn graph(edges: Vec<Vec<i32>>) -> Vec<Vec<usize>> {
      let n = edges.iter().map(|edge| edge[0].max(edge[1])).max().unwrap() as usize + 1;
      edges.into_iter()
          .fold(vec![Vec::new(); n], |mut graph, edge| {
              let (from, to) = (edge[0] as usize, edge[1] as usize);
              graph[from].push(to);
              graph[to].push(from);
              graph
          })
  }
#+end_src

* Пошук ступіню

На відміну від попередньої задачі, тут треба обчислити /кольорові ступіні/, які визначають найбільшу
кількість вузлів одного кольору, за умови, що кольори двох сусідніх вузлів не можуть бути однаковими. В
цьому випадку є тільки два /кольори/ (=color=) --- /парний/ (=even=) та непарний (=odd=), які можуть
також кодуватися логічними значеннями. Однак зручніше використовувати три значення, ~1~ і ~0~ для
непарного та парного кольору відповідно, і використовувати спеціальне значення ~-1~ для позначення
вузлів, які ще не пофарбовано.

Функція ~degree~ знаходить ступіні вузлів для заданого графа ~graph~. Важливо, що ступінь кожного вузла
того ж самого кольору є однаковим для усіх вузлів одного коліру. Оскільки ми маємо лише два кольори,
достатньо повернути масив масив з двох елементів ~degree~, де ~degree[0]~ є ступенем для парних вершин, а
~degree[1]~ --- для непарних. Крім того, нам також знадобиться повернути вектор кольорів для кожного
вузла, який використовується для обчислення ступенів окремих елементів першого графа.

#+begin_src rust :noweb yes :noweb-ref task3373:Визначення
  fn degree(graph: &Vec<Vec<usize>>) -> ([i32; 2], Vec<isize>) {
      <<task3373:degree:Дії>>
      (degree, colors)
  }
#+end_src

За умовами задачі у нас є, щонайменше, два вузла, тому для кожного ступіню початкове значення дорівнює
~1~. Однак, для простоти, почнемо з нульових значень, а необхідний підрахунок виконає стандартний
алгоритм.

#+begin_src rust :noweb-ref task3373:degree:Дії
  let mut degree = [0, 0];
#+end_src

Визначимо вектор кольорів для кожного вузла. Спочатку усі вузли, крім першого, не є пофарбованими. Для
визначеності почнемо пошук з вузла ~0~, який вважатимемо парним.

#+begin_src rust :noweb-ref task3373:degree:Дії
  let mut colors = vec![-1; graph.len()];
  colors[0] = 0;
#+end_src

Утворимо чергу ~queue~ для фарбування графа, яка спочатку містить вузол ~0~.

#+begin_src rust :noweb-ref task3373:degree:Дії
  let mut queue = vec![0];
#+end_src

Перебираємо чергу, поки вона не закінчиться і обробляємо кожний вузол.

#+begin_src rust :noweb yes :noweb-ref task3373:degree:Дії
  while let Some(node) = queue.pop() {
      <<task3373:degree:Обробити-вузол>>
  }
#+end_src

Зауважимо, що усі вузли в черзі завжди є пофарбованими. Тому просто збільшимо ступінь для поточного
кольору.

#+begin_src rust :noweb-ref task3373:degree:Обробити-вузол
  degree[colors[node] as usize] += 1;
#+end_src

Пофарбуємо усіх непофарбованих сусідів вузла, у протилежний колір і додамо їх до черги.

#+begin_src rust :noweb-ref task3373:degree:Обробити-вузол
  for &next in &graph[node] { if colors[next] == -1 {
      colors[next] = 1 - colors[node];
      queue.push(next)
  }}
#+end_src

* Пошук максимального ступіню другого графа

Знайдемо ступіні для обох кольорів у другому графі. Зауважимо, що вектор кольорів для нього можна
проігнорувати, оскільки нас цікавить лише найбільший ступінь. Результатом є максимальне з двох значень
~d~.

#+begin_src rust :noweb-ref task3373:Дії
  let (d, _) = degree(&graph(edges2));
  let d2 = d[0].max(d[1]);
#+end_src

* Пошук рішення

Для отримання рішення достатньо до ступіню кожного вузла в першому графі додати максимальний ступінь ~d~
другого графа (яке ми знайшли [[id:5fe68856-dcf8-43ff-b242-7284c4499286][раніше]], оскільки одне ребро буде додано під час з'єднання графів.

#+begin_src rust :noweb-ref task3373:Дії
  let g = graph(edges1);
  let (d, cs) = degree(&g);
  (0..g.len()).map(|n| d[cs[n] as usize] + d2).collect()
#+end_src 
