#+title: =Leetcode=, задача =724=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task724.rs
  <<task724:Декларації>>

  <<task724:Визначення>>

  pub fn pivot_index(nums: Vec<i32>) -> i32 {
      <<task724:Дії>>
  }

  fn main() {
      <<task724:Отримання-даних>>
      println!("{}", pivot_index(nums));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task724:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task724:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let nums: Vec<i32> = args[1]
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
#+end_src

Для зручності позначимо розмір масиву як ~n~.

#+begin_src rust :noweb-ref task724:Дії
  let n = nums.len();
#+end_src

* Початкові значення сум

Спочатку /ліва/ сума (=left=) дорівнює ~0~, а /права/ (=right=) --- суму всіх значень, крім першого.

#+begin_src rust :noweb-ref task724:Дії
  let mut left = 0;
  let mut right = nums.iter().skip(1).sum::<i32>();
#+end_src

* Обробка елементів

Обробляємо усі значення разом з їх індексами, крім останнього (з індексами від ~0~ до ~n-2~). Для кожного
значення визначаємо два випадки:

- ліва сума дорівнює правій; поточний індекс є результатом, повертаємо його;
- ліва сума не дорівнює правій; додаємо до лівої суми поточне значення, а від правої віднімаємо наступне
  (саме тому ми не включаємо в цикл останє значення).

Оскільки значення масива можуть бути від'ємними, суми не є монотонними, тому ми не можемо розраховувати
на те, що можна завершити цикл достроково, як тільки ліва сума стане більше правої, ми мусимо перебрати
усі значення до кінця. Якщо ми досягли кінця масива, необхідно виконати останню перевірку на рівність
сум, оскільки ми не перевіряли останній елемент.

#+begin_src rust :noweb-ref task724:Дії
  for i in 0..n-1 {
      if left == right { return i as i32; }
      left += nums[i];
      right -= nums[i+1];
  }
  if left == right { (n-1) as i32 } else { -1 }
#+end_src

