#+title: =Leetcode=, задача =2434=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task2434.rs
  <<task2434:Декларації>>

  <<task2434:Визначення>>

  pub fn robot_with_string(s: String) -> String {
      <<task2434:Дії>>
  }

  fn main() {
      <<task2434:Отримання-даних>>
      println!("{}", robot_with_string(s));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task2434:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task2434:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let s = args[1].clone();
#+end_src

* Отримання статистики

Зберемо у впорядкованій мапі (~BTreeMap~) ~cnts~ кількість кожної літери в рядку джерела
~s~. Впорядкована мапа тут потрібна, оскільки алгоритм порівнює верхню літеру стека з найменшою літерою в
залишку рядка.

#+begin_src rust :noweb-ref task2434:Декларації
  use std::collections::BTreeMap;
#+end_src

#+begin_src rust :noweb-ref task2434:Дії
  let mut cnts: BTreeMap<_, usize> = s.chars()
      .fold(BTreeMap::new(), |mut cnts, c| { *cnts.entry(c).or_default() += 1; cnts });
#+end_src

* Обробка літер

Обробимо почергово усі літери ~c~ з рядка джерела. Кожен такий символ розподілятимо між паперовим
результатом (~result~) та проміжним стеком ~t~. В кінці стек автоматично стає пустим.

#+begin_src rust :noweb yes :noweb-ref task2434:Дії
  let mut result = String::new();
  let mut t = Vec::new();
  for c in s.chars() {
      <<task2434:Обробити-літеру>>
  }
  result
#+end_src

Чергову літеру ~c~ поміщаємо до ~t~.

#+begin_src rust :noweb yes :noweb-ref task2434:Обробити-літеру
  t.push(c);
#+end_src

Зменшимо кількість літери ~c~ із статистики, і якщо кількість стає нульовою, вилучаємо цей запис цілком.

#+begin_src rust :noweb yes :noweb-ref task2434:Обробити-літеру
  ,*cnts.get_mut(&c).unwrap() -= 1;
  if *cnts.get_mut(&c).unwrap() == 0 { cnts.remove(&c); }
#+end_src

Після цього, поки ~t~ не пустий і верхня літера ~t~ не більше будь-якої літери в залишку ~s~, тобто, не
більше найменшого ключа в ~cnt~, виштовхуємо цю літеру і додаємо до результата. Для пустої статистики
вважаємо, що вона все ще містить найбільшу літеру ~z~, що призведе до виштовхування усіх літер, що
залишилися в ~t~.

#+begin_src rust :noweb yes :noweb-ref task2434:Обробити-літеру
  while !t.is_empty() && t.last().unwrap() <= cnts.first_key_value().map(|k| k.0).unwrap_or(&'z') {
      result.push(t.pop().unwrap());
  }
#+end_src

* Тести

#+begin_src rust :noweb yes :noweb-ref task2434:Визначення
  #[cfg(test)]
  mod tests {
      use super::*;

      #[test]
      fn test_basic_1() {
          let s = "zza".to_string();
          let result = robot_with_string(s);
          assert_eq!(result, "azz");
      }

      #[test]
      fn test_basic_2() {
          let s = "bac".to_string();
          let result = robot_with_string(s);
          assert_eq!(result, "abc");
      }

      #[test]
      fn test_basic_3() {
          let s = "bdda".to_string();
          let result = robot_with_string(s);
          assert_eq!(result, "addb");
      }

      #[test]
      fn test_complex() {
          let s = "bydizfve".to_string();
          let result = robot_with_string(s);
          assert_eq!(result, "bdevfziy");
      }

      fn test_from_file_impl(filename: &str) {
          use std::fs::File;
          use std::io::{BufRead, BufReader};

          let file = File::open(filename).unwrap();
          let mut lines = BufReader::new(file).lines();
          
          let input = lines.next().unwrap().unwrap();
          let expected = lines.next().unwrap().unwrap();
          
          let result = robot_with_string(input);
          assert_eq!(result, expected);
      }

      #[test]
      fn test_from_file_1() {
          test_from_file_impl("./task2434_1.txt");
      }

      #[test] 
      fn test_from_file_2() {
          test_from_file_impl("./task2434_2.txt");
      }
      
      #[test] 
      fn test_from_file_3() {
          test_from_file_impl("./task2434_3.txt");
      }
  }
#+end_src

