#+title: =Leetcode=, задача =2542=

Див. тестові файли [[file:task2542_1.txt][task2542_1.txt]], [[file:task2542_2.txt][task2542_2.txt]], [[file:task2542_3.txt][task2542_3.txt]]

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task2542.rs
  <<task2542:Декларації>>

  <<task2542:Визначення>>

  fn max_score(nums1: Vec<i32>, nums2: Vec<i32>, k: i32) -> i64 {
      <<task2542:Дії>>
      result
  }

  fn main() {
      <<task2542:Отримання-даних>>
      println!("{}", max_score(nums1, nums2, k));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task2542:Декларації
  use std::{env, fs, io::{self, BufRead}};
#+end_src

#+begin_src rust :noweb-ref task2542:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let file = fs::File::open(&args[1]).unwrap();
  let mut lines = io::BufReader::new(file)
      .lines()
      .map(|line| line.unwrap());
  let nums1 = lines.next().unwrap()
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
  let nums2 = lines.next().unwrap()
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
  let k = lines.next().unwrap().parse().unwrap();
#+end_src

Встановимо синонім розміру масивів ~n~.

#+begin_src rust :noweb-ref task2542:Дії
  let n = nums1.len();
#+end_src

Вирівняємо тип ~k~.

#+begin_src rust :noweb-ref task2542:Дії
  let k = k as usize;
#+end_src

* Формування масиву пар

Ідея рішення заключається в тому, щоб пов'язати значення з обох масивів в пари, відсортувати отриманий
масив пар, а потім перебирати елементи по зростанню другого компонента пари, намагаючись знайти найбільшу
суму з залишків перших компонент.

Тому спочатку знайдемо відсортований перелік пар.

#+begin_src rust :noweb-ref task2542:Дії
  let mut pairs = (0..n)
      .map(|i| (nums1[i], nums2[i]))
      .collect::<Vec<_>>();
  pairs.sort_by_key(|pair| pair.1);
#+end_src

* Пошук залишків

Пряма реалізація з перебором від менших значень другої послідовності до більших виявляється
неефективним. Замість цього будемо перебирати значення в зворотньому порядку.

Важливо правильно задати межі перебору, оскільки отримати ~k~ компонент можна, тільки якщо індекс не
більше ~n-k~. Починаємо з останьої пари з індексом ~n-k~. Для неї можна обчислити початкову суму з
~nums1~, при цьому можливий тільки один варіант. Потім беремо кожний попередній елемент, для нього сума
має бути збільшена на відповідне значення з ~nums1~, але з суми необхідно відняти найменше зі значень
справа від поточної пари. Для знаходження таких найменших значень використовуємо впорядковану суму
(~BinaryHeap~).

Враховуємо, що при множенні може виникнути переповнення, тому перед обчисленням добутку треба привести
обидва значення до ~i64~.

#+begin_src rust :noweb yes :noweb-ref task2542:Декларації
  use std::collections::BinaryHeap;
  use std::cmp::Reverse;
#+end_src

#+begin_src rust :noweb yes :noweb-ref task2542:Дії
  let (nums1, nums2): (Vec<_>, Vec<_>) = pairs.into_iter().unzip();
  let mut queue: BinaryHeap<_> = nums1[n-k..].iter().map(|&i| Reverse(i as i64)).collect();
  let mut sum: i64 = nums1[n-k..].iter().map(|&i| i as i64).sum();
  let mut result = nums2[n-k] as i64 * sum;
  for i in (0..n-k).rev() {
      sum += nums1[i] as i64 - queue.pop().unwrap().0;
      queue.push(Reverse(nums1[i] as i64));
      result = result.max(nums2[i] as i64 * sum);
  }
#+end_src
