#+title: =Leetcode=, задача =2563=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task2563.rs
  <<task2563:Декларації>>

  <<task2563:Визначення>>

  fn count_fair_pairs(mut nums: Vec<i32>, lower: i32, upper: i32) -> i64 {
      <<task2563:Дії>>
  }

  fn main() {
      <<task2563:Отримання-даних>>
      println!("{}", count_fair_pairs(nums, lower, upper));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task2563:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task2563:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let nums = args[1]
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
  let lower = args[2].parse().unwrap();
  let upper = args[3].parse().unwrap();
#+end_src

* Сортування

Відсортуємо джерело за зростанням, оскільки пошук пар відбувається від більших значень до менших.

#+begin_src rust :noweb-ref task2563:Дії
  nums.sort();
#+end_src

* Загальне рішення

Задача спрощується, коли ми спочатку знаходимо кількість пар, які не менше ~upper~, потім від цієї
кількості віднімаємо кількість пар, які не менше ~lower-1~.

При цьому обидва пошуки виконуються повністю однаково. Були сумніви, що другий пошук можна почати з того
місця, де закінчився перший пошук, і на цьому можна підвищити ефективність, однак це припущення виявилося
невірним. Тому результат оформлюється просто за допомогою функции ~count~.

#+begin_src rust :noweb-ref task2563:Дії
  count(&nums, upper) - count(&nums, lower - 1)
#+end_src

* Підрахунок пар
:PROPERTIES:
:ID:       ef472204-2373-4c8c-aba0-d0aa321d090a
:END:

#+begin_src rust :noweb yes :noweb-ref task2563:Визначення
  fn count(nums: &[i32], limit: i32) -> i64 {
      let mut result = 0;
      <<task2563:count:Дії>>
      result as i64
  }
#+end_src

Нехай індекс ~j~ рухається справа наліво, від більших значень до менших, починаючи з останнього
(найбільшого) значення. Для кожного значення ~j~ підрахуємо кількість пар у вигляді суми.

Оскільки ми не враховуємо варіант ~j=0~, випадок, коли ~n=1~ автоматично повертає нульовий результат.

#+begin_src rust :noweb yes :noweb-ref task2563:count:Дії
  for j in (1..nums.len()).rev() {
      <<task2563:count:Знайти-кількість-пар>>
  }
#+end_src

Знайдемо найбільший індекс ~i~ такий, що ~i<j~ і ~nums[i] + nums[j] <= limit~. Оскільки джерело
впорядковане за зростанням, значення ~i~ можна знайти [[id:cc6fb99c-bd37-4096-98f6-5397ba5bbca3][двійковим пошуком]]. Тут ми для простоти відділяємо
найбільший елемент ~j~ і виконуємо пошук тільки на відрізку від початку до ~j~ (виключно).

Якщо необхідний індекс ~i~ не знайдено, пропускаємо обробку. В іншому випадку ми отримуємо ~i+1~ пар, що,
підходять. Додаємо цю кількість до результату.

Однак, ми можемо виконати тут додаткову оптимізацію. Коли знайдений індекс ~i~ є найбільшим на відрізку
(тобто, безпосередньо передує ~j~, або ~i+1 = j~, нам нема сенсу перебирати далі ~j~, оскільки підходять
будь-які пари з діапазону, що залишився. Тому ми припиняємо перебір і повертаємо вже накопиченю кількість
плюс усі ~j*(j+1)/2~, що залишилися.

#+begin_src rust :noweb yes :noweb-ref task2563:count:Знайти-кількість-пар
  if let Some(i) = search(&nums[..j], nums[j], limit) {
      if i+1 == j {
          return (result + j * (j + 1) / 2) as i64;
      } else {
          result += i + 1;
      }
  }
#+end_src

* Двійковий пошук
:PROPERTIES:
:ID:       cc6fb99c-bd37-4096-98f6-5397ba5bbca3
:END:

Особливістю пошуку тут є те, що стандартний двійковий пошук є *нестабільним*, тобто, може повернути
будь-який елемент, який задовольняє умові. В нашому випадку ми маємо знайти *самий правий* елемент, що
вимагає особливої обробки лівої межи. Тому реалізуємо двійковий пошук явно.

Пошук може завершитись невдало, для визначення такого випадку використовуємо пустий результат.

#+begin_src rust :noweb yes :noweb-ref task2563:Визначення
  fn search(nums: &[i32], num: i32, limit: i32) -> Option<usize> {
      <<task2563:search:Дії>>
  }
#+end_src

Спочатку ліва межа ~l~ дорівнює ~0~, а права ~h~ вказує на останній елемент ~nums~.

#+begin_src rust :noweb-ref task2563:search:Дії
  let (mut l, mut h) = (0, nums.len() - 1);
#+end_src

Виконуємо пошук в циклі, поки обидві межі не співпадуть (~l=h~), або не стануть сусідніми (~h=l+1~). Ці
умови можна об'єднати в одну ~l+1>=h~, однак у якості умови циклу ми використовуємо її заперечення
~l+1<h~.

#+begin_src rust :noweb-ref task2563:search:Дії
  while l+1 < h {
      let m = (l + h) / 2;
      if nums[m] + num <= limit { l = m; } else { h = m; }
  }
#+end_src

Врахуємо, що якщо обидва індекси ~l~ і ~h~ співпадають (~l=h~), можна обрати будь-яке з них.

Перевіримо верхній індекс. Якщо його значення задовільняє умові, повертаємо верхній індекс, цей випадок
одинаково підходить і при ~l=h~, і при ~l+1=h~.

#+begin_src rust :noweb-ref task2563:search:Дії
  if nums[h] + num <= limit { return Some(h); }
#+end_src

Якщо верхнє значення не задовольняє умові, перевіримо нижнє значення. Якщо воно задовільняє, повертаємо
нижній індекс, якщо ні, то повертаємо пусте значення. Цей результат також підходить для обох випадків.

#+begin_src rust :noweb-ref task2563:search:Дії
  if nums[l] + num <= limit { Some(l) } else { None }
#+end_src
