#+title: =Leetcode=, задача =2179=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task2179.rs
  <<task2179:Декларації>>

  <<task2179:Визначення>>

  fn good_triplets(nums1: Vec<i32>, nums2: Vec<i32>) -> i64 {        
      <<task2179:Дії>>
  }

  fn main() {
      <<task2179:Отримання-даних>>
      println!("{}", good_triplets(nums1, nums2));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task2179:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task2179:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let nums1 = args[1]
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
  let nums2 = args[2]
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
#+end_src

Для зручності позначимо розміри масивів як ~n~.

#+begin_src rust :noweb-ref task2179:Дії
  let n = nums1.len();
#+end_src

* Отримання відображення

Перетворимо перший масив на масив індексів ~idcs~, який по суті є зворотньою перестановкою.

#+begin_src rust :noweb-ref task2179:Дії
  let idcs = nums1.into_iter().enumerate()
      .fold(vec![0; n], |mut idcs, (i, num)| {
          idcs[num as usize] = i;
          idcs
      });
#+end_src

Використовуючи цей масив, побудуємо комбінацію перестановок ~nums~, яка надасть відображення індексів другого
масива в перший.

#+begin_src rust :noweb-ref task2179:Дії
  let nums: Vec<_> = nums2.into_iter().map(|num| idcs[num as usize]).collect();
#+end_src

* Обчислення результата

** Ефективна реалізація

Для кожного індекса ~i~ в діапазоні ~1..n-1~ (тобто, виключаючи перше та останнє значення) треба для
~j=0..i~ підрахувати кількість ~lc~ (=l=-eft =c=-ount) значень ~nums[j]~, які суворо менше ~nums[i]~, а
для ~j=i+1..n~ кількість ~rc~ (=r=-ight =c=-ount) значень ~nums[j]~, які суворо більше
~nums[i]~. Результатом для ~i~ є добуток ~lc * rc~, а загальний результат --- це сума результатів для
усіх значень ~i~.

[[id:e7f13d8f-d8c1-4cbd-8aaa-3c2648cc84ae][Прямий перебір]] має складність ~O(n^2)~, що є неприйнятним для великих значень ~n~. Пропонується вирішити
проблему за допомогою [[id:c85d3225-62af-4a46-abec-0fbf21ba2caa][дерева Фенвіка]].

*** Два проходи

Ідея заключається в тому, щоб для кожного індекса брати значення ~nums~ як індекс і накопичувати для
цього значення, використовуючи його, як індекс, префікс-суми в дереві Фенвіка ~fw~. Тоді чергове значення
~fw~ дасть ~lc~ з ефективністю ~O(log(n))~ (замість ~O(n)~).

В результаті отримуємо ітератор ~lcs~ по кількості лівих елементів для кожного індексу.

#+begin_src rust :noweb-ref task2179:Дії
  let lcs = nums.iter()
      .scan(FenwickTree::new(n), |fw, &num| {
          fw.inc(num+1);
          Some(fw.get(num))
      });
#+end_src

Спроба обчислити кількість правих елементів ~rc~ [[id:21663d86-721b-4507-89b4-0ba10e65e91e][в тому ж самому проході]] виявилася невдалою. Тому для
правих елементів ми використовуємо аналогічний алгоритм, але обертаємо порядок в ~nums~ і
"віддзеркалюємо" його значення відносно ~n-1~ для обчислення послідовності, знову з деревом
Фенвіка. Потім перетворюємо результат на вектор і інвертуємо його (результат сканування не може бути
обернений). В результаті отримуємо ітератор по правим елементам.

#+begin_src rust :noweb-ref task2179:Дії
  let rcs = nums.iter().rev()
      .scan(FenwickTree::new(n), |fw, &num| {
          fw.inc(n-num);
          Some(fw.get(n-1-num))
      })
      .collect::<Vec<_>>().into_iter().rev();
#+end_src

Об'єднаємо резульати і обчислимо суму.

#+begin_src rust :noweb-ref task2179:Дії
  lcs.zip(rcs).map(|(lc, rc)| lc * rc).sum()
#+end_src

*** COMMENT Один прохід
:PROPERTIES:
:ID:       21663d86-721b-4507-89b4-0ba10e65e91e
:END:

Ідея одного проходу заключається в тому, щоб одразу підрахувати кількість правих елементів ~rc~,
проходячи індекси зліва направо. Відповідно до підказки це значення отримується як кількість
"необроблених" елементів справа від поточного. Для цього обчислюється загальна кількість значень справа
від поточного індекса ~n-1-i~, і від неї віднімається різниця між кількістю "оброблених" елементів
(~fw.get(n-1)~) і оброблених елементів зліва (~lc~), тобто, ~fw.get(n-1) - lc~. Загальна формула
~(n-1-i) - (fw.get(n-1) - lc)~ також виглядає, як магія.

На жаль, ця магія не працює.

#+begin_src rust :noweb-ref task2179:Дії
  println!("{:?}", nums);
  nums.iter().enumerate()
      .scan(FenwickTree::new(n), |fw, (i, &num)| {
          println!("T: {}", fw.get(n-1));
          let lc = fw.get(num);
          fw.inc(num+1);
          let rc1 = (i+1..n).filter(|&j| nums[j] > num).count() as i64;
          let rc2 = (n-1-i) as i64 - (fw.get(n-1) - lc);
          println!("{} = {}-({}-{}) = {}", rc1, (n-1-i), fw.get(n-1), lc, rc2);
          Some(lc * rc1)
      })
      .sum()
#+end_src

** COMMENT Прямий перебір
:PROPERTIES:
:ID:       e7f13d8f-d8c1-4cbd-8aaa-3c2648cc84ae
:END:

#+begin_src rust :noweb-ref task2179:Дії
  (1..n-1)
      .map(|i| {
          let lc = (0..i).filter(|&j| nums[j] < nums[i]).count() as i64;
          let rc = (i+1..n).filter(|&j| nums[j] > nums[i]).count() as i64;
          lc * rc
      })
      .sum()
#+end_src

* Дерево Фенвіка
:PROPERTIES:
:ID:       c85d3225-62af-4a46-abec-0fbf21ba2caa
:END:

/Дерево Фенвіка/, або [[https://en.wikipedia.org/wiki/Fenwick_tree][двійкове індексоване дерево]] (=BIT=, =B=-inary =I=-ndexed =T=-ree) дозволяє
ефективно обчислювати префікс-суми. Звичайний масив оновлюється за ~O(1)~, але після цього необхідні
префікс-суми обислюються за ~O(n)~. З іншого боку, масив префікс-сум повертає необхідну суму за ~O(1)~,
але оновлення такого масиву виконується за ~O(n)~. Дерево Фенвіка виконує обидві операції за ~O(log(n))~.

Для =Rust= існують стандартні реалізації [[https://docs.rs/fenwick/latest/fenwick/][дерева Фенвіка]], але в =Leetcode= неможливо скористатися,
оскільки це нестандартний крейт. Тому дерево Фенвіка реалізується окремо. При цьому враховуються
особливості задачі, що дозволяють спростити реалізацію.

Всередині дерево Фенвіка представлено як вектор значень.

#+begin_src rust :noweb yes :noweb-ref task2179:Визначення
  struct FenwickTree(Vec<i64>);

  impl FenwickTree {
      <<task2179:FenwickTree:Визначення>>
  }
#+end_src

** Створення

Для створення дерева використовується функція ~new~.

#+begin_src rust :noweb yes :noweb-ref task2179:FenwickTree:Визначення
  fn new(n: usize) -> Self { FenwickTree(vec![0; n + 1]) }
#+end_src

** Розмір

Зауважимо, що вектор представлення має на один елемент більше, ніж задається параметром ~n~. Тому для
корекції визначимо функцію ~len~, яка повертає реальний розмір.

#+begin_src rust :noweb yes :noweb-ref task2179:FenwickTree:Визначення
  fn len(&self) -> usize { self.0.len() - 1 }
#+end_src

** Оновлення

В загальному випадку елемент дерева оновлюється (=update=) за допомогою додавання деякого значення в
параметрі (=delta=). Однак, в цій задачі усі оновлення збільшують значення лише на фіксовану різницю ~1~,
тому замість загального оновлення реалізуємо просте нарощування (~inc~-rement).

В цілому алгоритм оновлення виглядає як магія, деталі якої можна зрозуміти, розібравшись з теорією для
дерева Фенвіка. Тут ми залишаємо реалізацію без описа.

Особливістю реалізації є те, що методи дерева приймають =0=-індекси, хоча стандартна реалізація
передбачає =1=-індекси. Для узгодження ми збільшуємо індекс на початку.

#+begin_src rust :noweb yes :noweb-ref task2179:FenwickTree:Визначення
  fn inc(&mut self, index: usize) {
      let mut index = index as isize + 1;
      while index as usize <= self.len() {
          self.0[index as usize] += 1;
          index += index & -index;
      }
  }
#+end_src

** Отримання значення

Отримання значення є такою ж магією, як і оновлення, тому також реалізуємо її без опису. Так само, як і з
оновленням, приводимо =0=-індекс до =1=-індексу.

#+begin_src rust :noweb yes :noweb-ref task2179:FenwickTree:Визначення
  fn get(&self, index: usize) -> i64 {
      let mut index = index as isize + 1;
      let mut result = 0;
      while index > 0 {
          result += self.0[index as usize];
          index -= index & -index;
      }
      result
  }
#+end_src

* Тести

#+begin_src text
  [5, 4, 3, 1, 7, 0, 2, 6]
  [3, 4, 6, 1, 7, 5, 0, 2]
  [0, 8, 6, 2, 3, 7, 1, 4, 5]
  [1, 7, 2, 3, 4, 5, 8, 6, 0]
  [3, 2, 10, 5, 6, 1, 7, 9, 4, 0, 8]
  [3, 4, 6, 5, 9, 10, 8, 7, 1, 0, 2]
  [8, 14, 12, 0, 7, 10, 1, 2, 6, 9, 13, 4, 11, 5, 15, 3]
  [9, 4, 11, 15, 13, 12, 0, 1, 2, 3, 14, 8, 7, 10, 5, 6]
  [3, 16, 9, 5, 14, 8, 15, 4, 10, 11, 1, 12, 2, 7, 6, 0, 13]
  [8, 13, 6, 10, 5, 12, 14, 11, 3, 2, 7, 9, 16, 15, 4, 1, 0]
  [3, 5, 6, 7, 1, 0, 2, 4]
  [4, 3, 6, 7, 1, 0, 2, 5]
  [3, 2, 1, 4, 0, 5]
  [2, 5, 3, 1, 0, 4]
  [1, 6, 7, 4, 10, 5, 0, 3, 9, 8, 13, 2, 11, 12]
  [10, 5, 8, 4, 2, 6, 12, 1, 9, 11, 3, 0, 7, 13]
#+end_src
