#+title: =Leetcode=, задача =3362=

Ця задача продовжує серію задач на /інкрементний масив/ (/difference array/), а саме, [[https://leetcode.com/problems/zero-array-transformation-i/solutions/6540070/difference-array-first-knowledge/][3355]] та [[https://leetcode.com/problems/zero-array-transformation-ii/solutions/6565954/tricky/][3356]]
(див. також [[file:src/bin/task3356.rs][task3356.rs]]).

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task3362.rs
  <<task3362:Декларації>>

  <<task3362:Визначення>>

  fn max_removal(mut nums: Vec<i32>, queries: Vec<Vec<i32>>) -> i32 {
      <<task3362:Дії>>
  }

  fn main() {
      <<task3362:Отримання-даних>>
      println!("{}", max_removal(nums, queries));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task3362:Декларації
  use std::{env, fs, io::{self, BufRead}};
#+end_src

#+begin_src rust :noweb-ref task3362:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let file = fs::File::open(&args[1]).unwrap();
  let mut lines = io::BufReader::new(file)
      .lines()
      .map(|line| line.unwrap());
  let nums = lines.next().unwrap()
      .trim_start_matches('[')
      .trim_end_matches(']')
      .split(',')
      .map(|item| item.parse().unwrap())
      .collect();
  let queries = lines.next().unwrap()
      .strip_prefix('[').unwrap()
      .strip_suffix(']').unwrap()
      .split("],[")
      .map(|row| row
           .trim_start_matches('[')
           .trim_end_matches(']')
           .split(',')
           .map(|item| item.parse().unwrap())
           .collect())
      .collect();
#+end_src

Для зручності позначимо розмір масива ~nums~ як ~n~, а розмір переліку запитів ~queries~ --- как ~m~.

#+begin_src rust :noweb-ref task3362:Дії
  let n = nums.len();
  let m = queries.len();
#+end_src

* Черга запитів

Алгоритм спираєтся на впорядковану /чергу запитів/. Спочатку вона була представлена у вигляді
впорядкованої сумки (~BinaryHeap~), але таке рішення виявилося неефективним.

Тому ми розподілимо усі запити в дворівневу структуру. На першому рівні це впорядкована мапа
(~BTreeMap~), ключом якої я ліва межа запиту. Значення ключів автоматично впорядковуються за
зростанням.

#+begin_src rust :noweb-ref task3362:Декларації
  use std::collections::BTreeMap;
#+end_src

Значенням мапи є впорядкована сумка (~BinaryHeap~), що містить усі значення правої межі у запитів, для
яких ліва межа є ключем.

#+begin_src rust :noweb-ref task3362:Декларації
  use std::collections::BinaryHeap;
#+end_src

Розподілимо запити.

#+begin_src rust :noweb-ref task3362:Дії
  let mut qs: BTreeMap<_, BinaryHeap<_>> = queries.into_iter()
      .fold(BTreeMap::new(), |mut qs, q| {
          qs.entry(q[0] as usize).or_default().push(q[1] as usize); qs
      });
#+end_src

* Інкрементний масив

Перетворимо вектор джерела на інкрементний масив, в якому усі елементи, окрім самого першого (~nums[0]~),
представлені різницею між цим та попереднім значенням. Для ефективності усі перетворення виконуємо прямо
в джерелі. Однак, оскільки інкрементний масив вимагає одного додаткового елемента, просто додамо ~0~ в
кінець масива.

#+begin_src rust :noweb-ref task3362:Дії
  nums.push(0);
  for i in (1..=n).rev() { nums[i] -= nums[i-1]; }
#+end_src

* Пошук рішення

Шукатимо рішення в безумовному циклі, який припиняється поверненням з функції в середині тіла
цикла. Таким чином, код після цикла є недоступним.

Особливістю задачі є те, що треба повернути не мінімальну кількість необхідних запитів, а максимальну
кількість запитів, яку можна викинути. Тому при підрахунку результат будемо зменшувати від початкової
кількості запитів, а не збільшувати.

#+begin_src rust :noweb yes :noweb-ref task3362:Дії
  let mut result = m as i32;
  let mut i = 0;
  loop {
      <<task3362:Знайти-рішення>>
  }
#+end_src

Оскільки метою є перетворення масива-джерела на нульовий, знайдемо перший ненульовий елемент. Для цього
відтворюємо головні значення з різниць. Неочевидною особливістю тут є те, що при ефективному обчисленні
результата запиту достатньо зменшувати одразу усі елементи в діапазоні запиту, і розглядати від'ємні
значення результата як "нульові", оскільки можна вважати, що зменшення цих значень не виконувалось. Тому
при пошуку достатньо знайти перше позитивне значення масива.

#+begin_src rust :noweb-ref task3362:Знайти-рішення
  while i < n && nums[i] <= 0 { i += 1; nums[i] += nums[i-1]; }
#+end_src

Якщо ми досягли кінця масива, то рішення знайдено, і можемо просто повернути результат.

#+begin_src rust :noweb-ref task3362:Знайти-рішення
  if i == n { return result; }
#+end_src

* Пошук наступного запиту

Для простоти виконуємо пошук в безумовному циклі. Кожний раз виштовхуємо перший елемент мапи, якщо це
неможливо, то рішення не існує, повертаємо ~-1~. Інакше порівнюємо ліву межу інтервала (ключ) з поточним
індексом ~i~:

- якщо ліва межа більше індекса, то поточний елемент неможливо зменшити, оскільки отримана межа є
  найменшою, і вона все одно правіше поточного індекса; рішення не існує, повертаємо ~-1~;
- якщо ліва межа дорівнює індекса, то ми знайшли елемент, що підходить, перериваємо пошук;
- якщо ліва межа менше, то всі інтервали для неї можна "урізати", перемісливши ліву межу у значення
  поточного індекса.

#+begin_src rust :noweb yes :noweb-ref task3362:Декларації
  use std::cmp::Ordering;
#+end_src

#+begin_src rust :noweb yes :noweb-ref task3362:Знайти-рішення
  let mut rs = loop {
      let Some((l, mut rs)) = qs.pop_first() else { return -1; };
      match l.cmp(&i) {
          Ordering::Greater => { return -1; },
          Ordering::Equal => { break rs; },
          Ordering::Less => { qs.entry(i).or_default().append(&mut rs); }
      }
  };
#+end_src

Зменшимо значення в масиві. Для ефективності будемо зменшувати поточне значення, поки воно більше ~0~,
або поки найбільша права межа (перша в сумці) більше поточного індекса. Якщо в якийсь момент усі значення
правої межі вичерпано, а значення все ще більше нуля, то рішення не існує, повертаємо ~-1~.

#+begin_src rust :noweb-ref task3362:Знайти-рішення
  while nums[i] > 0 {
      let Some(r) = rs.pop() else { return -1; };
      if r < i { return -1; } else {
          nums[i] -= 1; nums[r+1] += 1;
          result -= 1;
      }
  }
#+end_src

В кінці усі значення ~rs~, що не були використанні при зменшенні, повертаються до черги.

#+begin_src rust :noweb-ref task3362:Знайти-рішення
  qs.insert(i, rs);
#+end_src

