#+title: =Leetcode=, задача =407=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task407.rs
  <<task407:Декларації>>

  <<task407:Визначення>>

  fn main() {
      let mut result = 0;
      <<task407:Дії>>
      println!("{}", result);
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task407:Декларації
  use std::{env, fs, io::{self, BufRead}};
#+end_src

#+begin_src rust :noweb-ref task407:Дії
  let args: Vec<String> = env::args().collect();
  let file = fs::File::open(&args[1]).unwrap();
  let grid: Vec<Vec<i32>> = io::BufReader::new(file)
      .lines()
      .map(|line| line.unwrap())
      .next().unwrap()
      .strip_prefix('[').unwrap()
      .strip_suffix(']').unwrap()
      .split("],[")
      .map(|row| row
           .trim_start_matches('[')
           .trim_end_matches(']')
           .split(',')
           .map(|item| item.parse().unwrap())
           .collect())
      .collect();
#+end_src

Для зручності визначимо розміри дошки.

#+begin_src rust :noweb-ref task407:Дії
  let (rows, cols) = (grid.len(), grid[0].len());
#+end_src

* Ознака зберігання комірки

Коміркою вважаємо стовпчик, який може зберігати воду. Створимо матрицю ознак комірок.

#+begin_src rust :noweb-ref task407:Дії
  let mut is_kept = vec![vec![true; cols]; rows];
#+end_src

* Витоки

Для ефективності будемо зберігати витоки в окремому переліку.

#+begin_src rust :noweb yes :noweb-ref task407:Дії
  let mut leaks = Vec::new();
#+end_src

* Перебір рівнів

#+begin_src rust :noweb yes :noweb-ref task407:Дії
  let minl = *grid.iter().map(|row| row.iter().min().unwrap()).min().unwrap();
  let maxl = *grid.iter().map(|row| row.iter().max().unwrap()).max().unwrap();
  for l in minl..=maxl {
      <<task407:Обробити-рівень>>
  }
#+end_src

** Додавання нових витоків

На новому рівні можуть з'явитися нові витоки на кордоні дошки.

#+begin_src rust :noweb yes :noweb-ref task407:Обробити-рівень
  for r in 0..rows {
      if grid[r][0] == l { is_kept[r][0] = false; leaks.push((r, 0)); }
      if grid[r][cols - 1] == l { is_kept[r][cols - 1] = false; leaks.push((r, cols - 1)); }
  }

  for c in 1..(cols - 1) {
      if grid[0][c] == l { is_kept[0][c] = false; leaks.push((0, c)); }
      if grid[rows - 1][c] == l { is_kept[rows - 1][c] = false; leaks.push((rows - 1, c)); }
  }
#+end_src

** Обробка витоків

Перебираємо усі витоки, і помічаємо усіх їх сусідів, також як витоки. Ця дія має повторюватися для нових
витоків, поки не будуть розмічені всі витоки на цьому рівні. Для такого перебору використовуємо чергу
точок для обробки, яка спочатку містить тільки поточні витоки. Для ефективності спочатку вважаємо чергою
поточний перелік витоків, а в процесі обробки будуємо новий перелік витоків.

#+begin_src rust :noweb yes :noweb-ref task407:Обробити-рівень
  let mut queue = leaks;
  leaks = Vec::new();
#+end_src

При знаходжені нового витоку фіксуємо в результаті об'єм води, якій він може зберегти на нижчих рівнях.

#+begin_src rust :noweb yes :noweb-ref task407:Обробити-рівень
  while let Some((r, c)) = queue.pop() {
      leaks.push((r, c));
      for (dr, dc) in [(-1, 0), (0, 1), (1, 0), (0, -1)] {
          let (r1, c1) = (r as isize + dr, c as isize + dc);
          if r1 >= 0 && r1 < rows as isize
              && c1 >= 0 && c1 < cols as isize
              && grid[r1 as usize][c1 as usize] <= l {
                  let (r1, c1) = (r1 as usize, c1 as usize);
                  if is_kept[r1][c1] {
                      is_kept[r1][c1] = false;
                      result += (l - grid[r1 as usize][c1 as usize]) as usize;
                      queue.push((r1, c1));
                  }   
              }
      }
  }
#+end_src

* COMMENT Відлагодження

Функція ~show_cells~ показує стан комірок.

#+begin_src rust :noweb-ref task407:Визначення
  type Cells = Vec<Vec<bool>>;
#+end_src

#+begin_src rust :noweb-ref task407:Визначення
  fn show_cells(cells: &Cells) {
      for row in cells {
          for cell in row {
              print!("{} ", if *cell { "K" } else { "L" });
          }
          println!();
      }
      println!();
  }
#+end_src
cvt
