#+title: =Leetcode=, задача =3272=

* Головний файл

#+begin_src rust :noweb yes :tangle src/bin/task3272.rs
  <<task3272:Декларації>>

  <<task3272:Визначення>>

  fn count_good_integers(n: i32, k: i32) -> i64 {
      <<task3272:Дії>>
  }

  fn main() {
      <<task3272:Отримання-даних>>
      println!("{}", count_good_integers(n, k));
  }
#+end_src

* Отримання даних

#+begin_src rust :noweb-ref task3272:Декларації
  use std::env;
#+end_src

#+begin_src rust :noweb-ref task3272:Отримання-даних
  let args: Vec<String> = env::args().collect();
  let n = args[1].parse().unwrap();
  let k = args[2].parse().unwrap();
#+end_src

Приведемо типи параметрів.

#+begin_src rust :noweb-ref task3272:Дії
  let n = n as u32;
  let k = k as u64;
#+end_src

* Окремий випадок однозначних чисел

Подальший пошук працює тільки для ~n>1~, тому обробимо ~n=1~ як окремий випадок. В такому разі нам
достатньо підрахувати та повернути кількість цифр (чисел від ~1~ до ~9~ включно), які цілком діляться на
~k~.

#+begin_src rust :noweb-ref task3272:Дії
  if n == 1 { return (1..=9).filter(|d| d % k == 0).count() as i64; }
#+end_src

* Отримання добрих наборів

Знайдемо впорядковану множину (~BTreeSet~) /добрих наборів/ (=good set=). Кожен добрий набір є
впорядкованою сумкою (для простоти, це буде просто відсортований вектор) цифр деякого доброго числа, в
якій всі цифри також впорядковані за зростанням. Таке впорядкування необхідо, оскільки нам необхідно
підрахувати кількість перестановок, однак різні паліндроми можуть складатися з одного і того ж доброго
набору. Тому при пошуку наборів ми маємо вилучити дублікати.

При пошуку нам достатньо повністю перебрати ліву частину паліндрому, тому будемо працювати з половиною
довжини числа ~n2~. Тут можливі два різних випадка, коли ~n~ парне, або непарне. Для виявлення цих
випадків визначимо прапорець ~n_is_odd~ як ознаку непарності ~n~.

#+begin_src rust :noweb-ref task3272:Дії
  let n_is_odd = n % 2 == 1;
  let n2 = n / 2;
#+end_src

При пошуку паліндрома достатньо перебрати тільки ліву половину, яка не може починатися з ~0~. Це
відповідає діапазону ~10^(n/2-1)..10^(n/2)~. Особливість перебору така, що в варіанті для непарних ~n~
утворюється додатковий перелік паліндромів чисел для кожної цифри, яка може бути рівно посередині
паліндрому. Тому результатом обробки має бути вектор. Для парних ~n~ такий вектор або пустий (коли
паліндром не є добрим числом), або містить рівно один паліндром. Після цього ми маємо об'єднати такі
вектори в єдиний "плаский" вектор, тому використовуємо ~flat_map~.

В отриманому векторі для кожного паліндрому відсортуємо його цифри за зростанням, в результаті різні
паліндроми можуть стати одним набором, що утворить дублікати, які будуть вилучені в результаті утворення
множини добрих наборів.

#+begin_src rust :noweb yes :noweb-ref task3272:Декларації
  use std::collections::BTreeSet;
#+end_src

#+begin_src rust :noweb yes :noweb-ref task3272:Дії
  let goods: BTreeSet<Vec<_>> = (10_usize.pow(n2-1)..10_usize.pow(n2))
      .flat_map(|x| {
          <<task3272:Отримати-добрі-набори>>
      })
      .map(|s: Vec<_>| { let mut s = s; s.sort(); s })
      .collect();
#+end_src

При отриманні добрих наборів отримаємо представлення лівої половини паліндрому ~l~ (=l=-eft) у вигляді
рядка, а праву половину ~r~ (=r=-ight) --- як зеркальне відображення ~l~.

#+begin_src rust :noweb-ref task3272:Отримати-добрі-набори
  let l = x.to_string();
  let r: String = l.chars().rev().collect();
#+end_src

Обробимо окремо парні та непарні значення ~n~.

#+begin_src rust :noweb yes :noweb-ref task3272:Отримати-добрі-набори
  if n_is_odd {
      <<task3272:Отримати-непарні-добрі-набори>>
  } else {
      <<task3272:Отримати-парні-добрі-набори>>
  }
#+end_src

Для парних добрих наборів отримаємо повний паліндром.

#+begin_src rust :noweb-ref task3272:Отримати-парні-добрі-набори
  let s = l.clone() + &r;
#+end_src

Якщо числове значення такого паліндрома цілком ділиться на ~k~, повертаємо вектор з цим значенням, інакше
повертаємо пустий вектор результату.

#+begin_src rust :noweb-ref task3272:Отримати-парні-добрі-набори
  if s.parse::<u64>().unwrap() % k == 0 { vec![s.chars().collect()] } else { vec![] }
#+end_src

Для непарних наборів треба додатково перебрати "центральну" цифру паліндрома, а сам повний паліндром має
включати цю цифру посередині. Однак, ми все ще маємо відібрати тільки ті паліндроми, що цілком діляться
на ~k~.

#+begin_src rust :noweb-ref task3272:Отримати-непарні-добрі-набори
  ('0'..='9')
      .filter_map(|d| {
          let s = l.clone() + &d.to_string() + &r;
          if s.parse::<u64>().unwrap() % k > 0 { None } else {
              Some(s.chars().collect())
          }
      })
      .collect()
#+end_src

* TODO Підрахунок перестановок

Кожний добрий набір породжує усі добрі числа перестановками. Після обчислень для кожного набора достатньо
скласти всі результати.

#+begin_src rust :noweb yes :noweb-ref task3272:Дії
  goods.into_iter()
      .map(|s| {
          <<task3272:Отримати-результат-для-набору>>
          result
      })
      .sum::<u64>() as i64
#+end_src

При обчисленні результату для одного набору необхідно врахувати два моменти:

- цифри можуть повторюватись, тому загальну кількість перестановок ~n!~ необхідно поділити на ~m[i]!~, де
  ~m[i]~ --- кількість кожної цифри в наборі.
- цифра ~0~ не може з'являтися на першому місці; тому з загальної кількості наборів після попереднього
  скорочення необхідно відняти перестановки, що починаються з нуля; це означатиме, що ми маємо так само
  обчислити кількість перестановок, але вже для більш короткого вектора перестановок довжини ~n-1~.

Отримаємо вектор кількостей кожної цифри в наборі.

#+begin_src rust :noweb yes :noweb-ref task3272:Отримати-результат-для-набору
  let mut cs = s.iter().skip(1)
      .fold((s[0], vec![1]), |(pv, cs), &v| {
          let mut cs = cs;
          if v == pv { *cs.last_mut().unwrap() += 1; } else { cs.push(1); }
          (v, cs)
      }).1;
#+end_src

Обчислюємо загальну кількість перестановок, враховуючи ті, що мають нуль на першому місці. Ця кількість
починається з ~n!~, а потім ділиться на факторіал кожного лічильника ~cs~. Для ефективності пропускаємо
одиничні значення.

Для підвищення точності визначимо ~n~ з підвищенною точністю.

#+begin_src rust :noweb yes :noweb-ref task3272:Отримати-результат-для-набору
  let n = n as u64;
  let mut result = cs.iter().filter(|&&c| c > 1)
      .fold((1..=n).product::<u64>(), |result, &c| result / (1..=c).product::<u64>());
#+end_src

Якщо першою цифрою набора є нуль (~'0'~), ми маємо відняти від результата кількість усіх комбінацій, які
починаються з нуля. При цьому загальна довжина набору є ~n-1~, а перше значення в ~cs[0]~ також
зменшується на ~1~. Навіть якщо в комбінації тільки один нуль, відповідний лічильник стане нульовим і
буде відкинутий при переборі. В іншому все повторюється.

#+begin_src rust :noweb yes :noweb-ref task3272:Отримати-результат-для-набору
  if s[0] == '0' {
      cs[0] -= 1;
      result -= cs.into_iter().filter(|&c| c > 1)
          .fold((1..=n-1).product::<u64>(), |result, c| result / (1..=c).product::<u64>());
  }
#+end_src
